//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:52:02 AM COT 
//


package org.dvb.pcf.pcf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.dvb.pcf.pcf_types.PcfItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dvb.org/pcf/pcf-types}pcfItemType">
 *       &lt;group ref="{http://www.dvb.org/pcf/pcf}substates" maxOccurs="unbounded"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "substates"
})
@XmlRootElement(name = "StateCollection")
public class StateCollection
    extends PcfItemType
{

    @XmlElements({
        @XmlElement(name = "State", type = State.class),
        @XmlElement(name = "JunctionState", type = JunctionState.class),
        @XmlElement(name = "ChoiceState", type = ChoiceState.class)
    })
    protected List<PcfItemType> substates;

    /**
     * Gets the value of the substates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link State }
     * {@link JunctionState }
     * {@link ChoiceState }
     * 
     * 
     */
    public List<PcfItemType> getSubstates() {
        if (substates == null) {
            substates = new ArrayList<PcfItemType>();
        }
        return this.substates;
    }

}
