//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.mpeg21._2011;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodecCapabilitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodecCapabilitiesType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2011}TerminalCapabilityBaseType">
 *       &lt;sequence>
 *         &lt;element name="Decoding" type="{urn:tva:mpeg21:2011}CodecCapabilityBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Encoding" type="{urn:tva:mpeg21:2011}CodecCapabilityBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodecCapabilitiesType", propOrder = {
    "decoding",
    "encoding"
})
public class CodecCapabilitiesType
    extends TerminalCapabilityBaseType
{

    @XmlElement(name = "Decoding")
    protected List<CodecCapabilityBaseType> decoding;
    @XmlElement(name = "Encoding")
    protected List<CodecCapabilityBaseType> encoding;

    /**
     * Gets the value of the decoding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decoding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecoding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodecCapabilityBaseType }
     * 
     * 
     */
    public List<CodecCapabilityBaseType> getDecoding() {
        if (decoding == null) {
            decoding = new ArrayList<CodecCapabilityBaseType>();
        }
        return this.decoding;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encoding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncoding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodecCapabilityBaseType }
     * 
     * 
     */
    public List<CodecCapabilityBaseType> getEncoding() {
        if (encoding == null) {
            encoding = new ArrayList<CodecCapabilityBaseType>();
        }
        return this.encoding;
    }

}
