//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.mpeg21._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ColorVisionDeficiencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColorVisionDeficiencyType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2011}DIABaseType">
 *       &lt;sequence>
 *         &lt;element name="DeficiencyType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="Red-Deficiency"/>
 *               &lt;enumeration value="Green-Deficiency"/>
 *               &lt;enumeration value="Blue-Deficiency"/>
 *               &lt;enumeration value="CompleteColorBlindness"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeficiencyDegree" type="{urn:tva:mpeg21:2011}VisualImpairmentDegreeType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorVisionDeficiencyType", propOrder = {
    "deficiencyType",
    "deficiencyDegree"
})
public class ColorVisionDeficiencyType
    extends DIABaseType
{

    @XmlElement(name = "DeficiencyType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deficiencyType;
    @XmlElement(name = "DeficiencyDegree", required = true)
    protected VisualImpairmentDegreeType deficiencyDegree;

    /**
     * Gets the value of the deficiencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeficiencyType() {
        return deficiencyType;
    }

    /**
     * Sets the value of the deficiencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeficiencyType(String value) {
        this.deficiencyType = value;
    }

    /**
     * Gets the value of the deficiencyDegree property.
     * 
     * @return
     *     possible object is
     *     {@link VisualImpairmentDegreeType }
     *     
     */
    public VisualImpairmentDegreeType getDeficiencyDegree() {
        return deficiencyDegree;
    }

    /**
     * Sets the value of the deficiencyDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualImpairmentDegreeType }
     *     
     */
    public void setDeficiencyDegree(VisualImpairmentDegreeType value) {
        this.deficiencyDegree = value;
    }

}
