//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.mpeg21._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import tva.mpeg7._2008.ControlledTermUseType;


/**
 * <p>Java class for DeviceClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceClassType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2011}TerminalCapabilityBaseType">
 *       &lt;sequence>
 *         &lt;element name="DeviceClass" type="{urn:tva:mpeg7:2008}ControlledTermUseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceClassType", propOrder = {
    "deviceClass"
})
public class DeviceClassType
    extends TerminalCapabilityBaseType
{

    @XmlElement(name = "DeviceClass")
    protected ControlledTermUseType deviceClass;

    /**
     * Gets the value of the deviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledTermUseType }
     *     
     */
    public ControlledTermUseType getDeviceClass() {
        return deviceClass;
    }

    /**
     * Sets the value of the deviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledTermUseType }
     *     
     */
    public void setDeviceClass(ControlledTermUseType value) {
        this.deviceClass = value;
    }

}
