//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.mpeg21._2011;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NaturalEnvironmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NaturalEnvironmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2011}DIABaseType">
 *       &lt;sequence>
 *         &lt;element name="NaturalEnvironmentCharacteristic" type="{urn:tva:mpeg21:2011}NaturalEnvironmentCharacteristicBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NaturalEnvironmentType", propOrder = {
    "naturalEnvironmentCharacteristic"
})
public class NaturalEnvironmentType
    extends DIABaseType
{

    @XmlElement(name = "NaturalEnvironmentCharacteristic")
    protected List<NaturalEnvironmentCharacteristicBaseType> naturalEnvironmentCharacteristic;

    /**
     * Gets the value of the naturalEnvironmentCharacteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the naturalEnvironmentCharacteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNaturalEnvironmentCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NaturalEnvironmentCharacteristicBaseType }
     * 
     * 
     */
    public List<NaturalEnvironmentCharacteristicBaseType> getNaturalEnvironmentCharacteristic() {
        if (naturalEnvironmentCharacteristic == null) {
            naturalEnvironmentCharacteristic = new ArrayList<NaturalEnvironmentCharacteristicBaseType>();
        }
        return this.naturalEnvironmentCharacteristic;
    }

}
