//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.mpeg21._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PresentationPriorityPreferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PresentationPriorityPreferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:mpeg21:2011}UserCharacteristicBaseType">
 *       &lt;sequence>
 *         &lt;element name="GeneralResourcePriorities" type="{urn:tva:mpeg21:2011}GeneralResourcePrioritiesType" minOccurs="0"/>
 *         &lt;element name="SpecificResourcePriorities" type="{urn:tva:mpeg21:2011}SpecificResourcePrioritiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PresentationPriorityPreferenceType", propOrder = {
    "generalResourcePriorities",
    "specificResourcePriorities"
})
public class PresentationPriorityPreferenceType
    extends UserCharacteristicBaseType
{

    @XmlElement(name = "GeneralResourcePriorities")
    protected GeneralResourcePrioritiesType generalResourcePriorities;
    @XmlElement(name = "SpecificResourcePriorities")
    protected SpecificResourcePrioritiesType specificResourcePriorities;

    /**
     * Gets the value of the generalResourcePriorities property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralResourcePrioritiesType }
     *     
     */
    public GeneralResourcePrioritiesType getGeneralResourcePriorities() {
        return generalResourcePriorities;
    }

    /**
     * Sets the value of the generalResourcePriorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralResourcePrioritiesType }
     *     
     */
    public void setGeneralResourcePriorities(GeneralResourcePrioritiesType value) {
        this.generalResourcePriorities = value;
    }

    /**
     * Gets the value of the specificResourcePriorities property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificResourcePrioritiesType }
     *     
     */
    public SpecificResourcePrioritiesType getSpecificResourcePriorities() {
        return specificResourcePriorities;
    }

    /**
     * Sets the value of the specificResourcePriorities property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificResourcePrioritiesType }
     *     
     */
    public void setSpecificResourcePriorities(SpecificResourcePrioritiesType value) {
        this.specificResourcePriorities = value;
    }

}
