//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.interstitial._2011;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tva.metadata.interstitial._2011 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tva.metadata.interstitial._2011
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link ConstantValueType }
     * 
     */
    public ConstantValueType createConstantValueType() {
        return new ConstantValueType();
    }

    /**
     * Create an instance of {@link ContentRefType }
     * 
     */
    public ContentRefType createContentRefType() {
        return new ContentRefType();
    }

    /**
     * Create an instance of {@link RuleMethodType }
     * 
     */
    public RuleMethodType createRuleMethodType() {
        return new RuleMethodType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link ReplacementPodType }
     * 
     */
    public ReplacementPodType createReplacementPodType() {
        return new ReplacementPodType();
    }

    /**
     * Create an instance of {@link RulesType }
     * 
     */
    public RulesType createRulesType() {
        return new RulesType();
    }

    /**
     * Create an instance of {@link ContentListType }
     * 
     */
    public ContentListType createContentListType() {
        return new ContentListType();
    }

    /**
     * Create an instance of {@link InterstitialBreakType }
     * 
     */
    public InterstitialBreakType createInterstitialBreakType() {
        return new InterstitialBreakType();
    }

    /**
     * Create an instance of {@link PredicateBagType }
     * 
     */
    public PredicateBagType createPredicateBagType() {
        return new PredicateBagType();
    }

    /**
     * Create an instance of {@link RuleRefType }
     * 
     */
    public RuleRefType createRuleRefType() {
        return new RuleRefType();
    }

    /**
     * Create an instance of {@link TermConstraintsType }
     * 
     */
    public TermConstraintsType createTermConstraintsType() {
        return new TermConstraintsType();
    }

    /**
     * Create an instance of {@link SpotSubstitutionType }
     * 
     */
    public SpotSubstitutionType createSpotSubstitutionType() {
        return new SpotSubstitutionType();
    }

    /**
     * Create an instance of {@link TargetingTableType }
     * 
     */
    public TargetingTableType createTargetingTableType() {
        return new TargetingTableType();
    }

    /**
     * Create an instance of {@link OtherRuleLanguageType }
     * 
     */
    public OtherRuleLanguageType createOtherRuleLanguageType() {
        return new OtherRuleLanguageType();
    }

    /**
     * Create an instance of {@link RulesTableType }
     * 
     */
    public RulesTableType createRulesTableType() {
        return new RulesTableType();
    }

    /**
     * Create an instance of {@link InterstitialTableType }
     * 
     */
    public InterstitialTableType createInterstitialTableType() {
        return new InterstitialTableType();
    }

    /**
     * Create an instance of {@link PodSubstitutionType }
     * 
     */
    public PodSubstitutionType createPodSubstitutionType() {
        return new PodSubstitutionType();
    }

    /**
     * Create an instance of {@link PredicateType }
     * 
     */
    public PredicateType createPredicateType() {
        return new PredicateType();
    }

    /**
     * Create an instance of {@link TargetingControlledTermsType }
     * 
     */
    public TargetingControlledTermsType createTargetingControlledTermsType() {
        return new TargetingControlledTermsType();
    }

    /**
     * Create an instance of {@link RecordingCacheType }
     * 
     */
    public RecordingCacheType createRecordingCacheType() {
        return new RecordingCacheType();
    }

}
