//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.interstitial._2011;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PredicateBag" type="{urn:tva:metadata:interstitial:2011}PredicateBagType"/>
 *           &lt;element name="Predicate" type="{urn:tva:metadata:interstitial:2011}PredicateType"/>
 *           &lt;element name="RuleRef" type="{urn:tva:metadata:interstitial:2011}RuleRefType"/>
 *         &lt;/choice>
 *         &lt;element name="OtherRuleLanguage" type="{urn:tva:metadata:interstitial:2011}OtherRuleLanguageType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:tva:metadata:2011}fragmentIdentification"/>
 *       &lt;attribute name="rule_id" type="{urn:tva:metadata:2011}TVAIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleType", propOrder = {
    "predicateBagOrPredicateOrRuleRef",
    "otherRuleLanguage"
})
public class RuleType {

    @XmlElements({
        @XmlElement(name = "PredicateBag", type = PredicateBagType.class),
        @XmlElement(name = "Predicate", type = PredicateType.class),
        @XmlElement(name = "RuleRef", type = RuleRefType.class)
    })
    protected List<Object> predicateBagOrPredicateOrRuleRef;
    @XmlElement(name = "OtherRuleLanguage")
    protected List<OtherRuleLanguageType> otherRuleLanguage;
    @XmlAttribute(name = "rule_id")
    protected String ruleId;
    @XmlAttribute(name = "fragmentId")
    protected String fragmentId;
    @XmlAttribute(name = "fragmentVersion")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger fragmentVersion;
    @XmlAttribute(name = "fragmentExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fragmentExpirationDate;

    /**
     * Gets the value of the predicateBagOrPredicateOrRuleRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predicateBagOrPredicateOrRuleRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredicateBagOrPredicateOrRuleRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PredicateBagType }
     * {@link PredicateType }
     * {@link RuleRefType }
     * 
     * 
     */
    public List<Object> getPredicateBagOrPredicateOrRuleRef() {
        if (predicateBagOrPredicateOrRuleRef == null) {
            predicateBagOrPredicateOrRuleRef = new ArrayList<Object>();
        }
        return this.predicateBagOrPredicateOrRuleRef;
    }

    /**
     * Gets the value of the otherRuleLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRuleLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherRuleLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherRuleLanguageType }
     * 
     * 
     */
    public List<OtherRuleLanguageType> getOtherRuleLanguage() {
        if (otherRuleLanguage == null) {
            otherRuleLanguage = new ArrayList<OtherRuleLanguageType>();
        }
        return this.otherRuleLanguage;
    }

    /**
     * Gets the value of the ruleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * Sets the value of the ruleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleId(String value) {
        this.ruleId = value;
    }

    /**
     * Gets the value of the fragmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId() {
        return fragmentId;
    }

    /**
     * Sets the value of the fragmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId(String value) {
        this.fragmentId = value;
    }

    /**
     * Gets the value of the fragmentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFragmentVersion() {
        return fragmentVersion;
    }

    /**
     * Sets the value of the fragmentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFragmentVersion(BigInteger value) {
        this.fragmentVersion = value;
    }

    /**
     * Gets the value of the fragmentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFragmentExpirationDate() {
        return fragmentExpirationDate;
    }

    /**
     * Sets the value of the fragmentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFragmentExpirationDate(XMLGregorianCalendar value) {
        this.fragmentExpirationDate = value;
    }

}
