//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.interstitial._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleMethodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MethodParameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" minOccurs="0"/>
 *           &lt;element name="RuleMethod" type="{urn:tva:metadata:interstitial:2011}RuleMethodType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="methodName" use="required" type="{urn:tva:mpeg7:2008}termReferenceType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleMethodType", propOrder = {
    "methodParameter",
    "ruleMethod"
})
public class RuleMethodType {

    @XmlElement(name = "MethodParameter")
    @XmlSchemaType(name = "anySimpleType")
    protected Object methodParameter;
    @XmlElement(name = "RuleMethod")
    protected RuleMethodType ruleMethod;
    @XmlAttribute(name = "methodName", required = true)
    protected String methodName;

    /**
     * Gets the value of the methodParameter property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMethodParameter() {
        return methodParameter;
    }

    /**
     * Sets the value of the methodParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMethodParameter(Object value) {
        this.methodParameter = value;
    }

    /**
     * Gets the value of the ruleMethod property.
     * 
     * @return
     *     possible object is
     *     {@link RuleMethodType }
     *     
     */
    public RuleMethodType getRuleMethod() {
        return ruleMethod;
    }

    /**
     * Sets the value of the ruleMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleMethodType }
     *     
     */
    public void setRuleMethod(RuleMethodType value) {
        this.ruleMethod = value;
    }

    /**
     * Gets the value of the methodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the value of the methodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

}
