//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import tva.metadata._2011.ControlledTermType;


/**
 * <p>Java class for ContentPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentPropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContentType" type="{urn:tva:metadata:2011}ControlledTermType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FileProperties" type="{urn:tva:metadata:extended:2011}FilePropertiesType" minOccurs="0"/>
 *         &lt;element name="ContentAttributes" type="{urn:tva:metadata:extended:2011}ContentAttributesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContextAttributes" type="{urn:tva:metadata:extended:2011}ContextAttributesType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentPropertiesType", propOrder = {
    "contentType",
    "fileProperties",
    "contentAttributes",
    "contextAttributes"
})
public class ContentPropertiesType {

    @XmlElement(name = "ContentType")
    protected List<ControlledTermType> contentType;
    @XmlElement(name = "FileProperties")
    protected FilePropertiesType fileProperties;
    @XmlElement(name = "ContentAttributes")
    protected List<ContentAttributesType> contentAttributes;
    @XmlElement(name = "ContextAttributes")
    protected List<ContextAttributesType> contextAttributes;

    /**
     * Gets the value of the contentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlledTermType }
     * 
     * 
     */
    public List<ControlledTermType> getContentType() {
        if (contentType == null) {
            contentType = new ArrayList<ControlledTermType>();
        }
        return this.contentType;
    }

    /**
     * Gets the value of the fileProperties property.
     * 
     * @return
     *     possible object is
     *     {@link FilePropertiesType }
     *     
     */
    public FilePropertiesType getFileProperties() {
        return fileProperties;
    }

    /**
     * Sets the value of the fileProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilePropertiesType }
     *     
     */
    public void setFileProperties(FilePropertiesType value) {
        this.fileProperties = value;
    }

    /**
     * Gets the value of the contentAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentAttributesType }
     * 
     * 
     */
    public List<ContentAttributesType> getContentAttributes() {
        if (contentAttributes == null) {
            contentAttributes = new ArrayList<ContentAttributesType>();
        }
        return this.contentAttributes;
    }

    /**
     * Gets the value of the contextAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextAttributesType }
     * 
     * 
     */
    public List<ContextAttributesType> getContextAttributes() {
        if (contextAttributes == null) {
            contextAttributes = new ArrayList<ContextAttributesType>();
        }
        return this.contextAttributes;
    }

}
