//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import tva.mpeg7._2008.TextualType;


/**
 * <p>Java class for CouponDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CouponDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="RequiredCoupon" type="{urn:tva:metadata:extended:2011}RequiredCouponType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="NonTVACouponRef" type="{urn:tva:metadata:extended:2011}NonTVACouponRefType" minOccurs="0"/>
 *           &lt;sequence minOccurs="0">
 *             &lt;element name="CouponValue" type="{urn:tva:metadata:extended:2011}CouponValueType"/>
 *             &lt;element name="ContentTarget" type="{urn:tva:metadata:extended:2011}ContentTargetType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="CouponURL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="CouponText" type="{urn:tva:mpeg7:2008}TextualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="UserTargetingInformation" type="{urn:tva:metadata:extended:2011}TargetingInformationType"/>
 *           &lt;element name="UserTargetingInformationRef" type="{urn:tva:metadata:2011}TVAIDRefType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="couponId" type="{urn:tva:metadata:2011}TVAIDType" />
 *       &lt;attribute name="authorityName" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="requiredNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="acquisitionMode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="immediate"/>
 *             &lt;enumeration value="linkedToContent"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CouponDescriptionType", propOrder = {
    "requiredCoupon",
    "nonTVACouponRef",
    "couponValue",
    "contentTarget",
    "couponURL",
    "couponText",
    "userTargetingInformationOrUserTargetingInformationRef"
})
public class CouponDescriptionType {

    @XmlElement(name = "RequiredCoupon")
    protected List<RequiredCouponType> requiredCoupon;
    @XmlElement(name = "NonTVACouponRef")
    protected NonTVACouponRefType nonTVACouponRef;
    @XmlElement(name = "CouponValue")
    protected CouponValueType couponValue;
    @XmlElement(name = "ContentTarget")
    protected List<ContentTargetType> contentTarget;
    @XmlElement(name = "CouponURL")
    @XmlSchemaType(name = "anyURI")
    protected String couponURL;
    @XmlElement(name = "CouponText")
    protected List<TextualType> couponText;
    @XmlElements({
        @XmlElement(name = "UserTargetingInformation", type = TargetingInformationType.class),
        @XmlElement(name = "UserTargetingInformationRef", type = String.class)
    })
    protected List<Object> userTargetingInformationOrUserTargetingInformationRef;
    @XmlAttribute(name = "couponId")
    protected String couponId;
    @XmlAttribute(name = "authorityName")
    @XmlSchemaType(name = "anyURI")
    protected String authorityName;
    @XmlAttribute(name = "requiredNumber")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger requiredNumber;
    @XmlAttribute(name = "start")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar start;
    @XmlAttribute(name = "end")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar end;
    @XmlAttribute(name = "acquisitionMode")
    protected String acquisitionMode;

    /**
     * Gets the value of the requiredCoupon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiredCoupon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiredCoupon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequiredCouponType }
     * 
     * 
     */
    public List<RequiredCouponType> getRequiredCoupon() {
        if (requiredCoupon == null) {
            requiredCoupon = new ArrayList<RequiredCouponType>();
        }
        return this.requiredCoupon;
    }

    /**
     * Gets the value of the nonTVACouponRef property.
     * 
     * @return
     *     possible object is
     *     {@link NonTVACouponRefType }
     *     
     */
    public NonTVACouponRefType getNonTVACouponRef() {
        return nonTVACouponRef;
    }

    /**
     * Sets the value of the nonTVACouponRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonTVACouponRefType }
     *     
     */
    public void setNonTVACouponRef(NonTVACouponRefType value) {
        this.nonTVACouponRef = value;
    }

    /**
     * Gets the value of the couponValue property.
     * 
     * @return
     *     possible object is
     *     {@link CouponValueType }
     *     
     */
    public CouponValueType getCouponValue() {
        return couponValue;
    }

    /**
     * Sets the value of the couponValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponValueType }
     *     
     */
    public void setCouponValue(CouponValueType value) {
        this.couponValue = value;
    }

    /**
     * Gets the value of the contentTarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentTarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentTargetType }
     * 
     * 
     */
    public List<ContentTargetType> getContentTarget() {
        if (contentTarget == null) {
            contentTarget = new ArrayList<ContentTargetType>();
        }
        return this.contentTarget;
    }

    /**
     * Gets the value of the couponURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponURL() {
        return couponURL;
    }

    /**
     * Sets the value of the couponURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponURL(String value) {
        this.couponURL = value;
    }

    /**
     * Gets the value of the couponText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the couponText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCouponText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextualType }
     * 
     * 
     */
    public List<TextualType> getCouponText() {
        if (couponText == null) {
            couponText = new ArrayList<TextualType>();
        }
        return this.couponText;
    }

    /**
     * Gets the value of the userTargetingInformationOrUserTargetingInformationRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userTargetingInformationOrUserTargetingInformationRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserTargetingInformationOrUserTargetingInformationRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetingInformationType }
     * {@link String }
     * 
     * 
     */
    public List<Object> getUserTargetingInformationOrUserTargetingInformationRef() {
        if (userTargetingInformationOrUserTargetingInformationRef == null) {
            userTargetingInformationOrUserTargetingInformationRef = new ArrayList<Object>();
        }
        return this.userTargetingInformationOrUserTargetingInformationRef;
    }

    /**
     * Gets the value of the couponId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * Sets the value of the couponId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponId(String value) {
        this.couponId = value;
    }

    /**
     * Gets the value of the authorityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * Sets the value of the authorityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorityName(String value) {
        this.authorityName = value;
    }

    /**
     * Gets the value of the requiredNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequiredNumber() {
        return requiredNumber;
    }

    /**
     * Sets the value of the requiredNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequiredNumber(BigInteger value) {
        this.requiredNumber = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStart(XMLGregorianCalendar value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnd(XMLGregorianCalendar value) {
        this.end = value;
    }

    /**
     * Gets the value of the acquisitionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionMode() {
        return acquisitionMode;
    }

    /**
     * Sets the value of the acquisitionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionMode(String value) {
        this.acquisitionMode = value;
    }

}
