//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tva.metadata.extended._2011 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SystemInformationTypeRAM_QNAME = new QName("urn:tva:metadata:extended:2011", "RAM");
    private final static QName _SystemInformationTypeCPU_QNAME = new QName("urn:tva:metadata:extended:2011", "CPU");
    private final static QName _SystemInformationTypeMiddleWare_QNAME = new QName("urn:tva:metadata:extended:2011", "MiddleWare");
    private final static QName _SystemInformationTypeSupportingOS_QNAME = new QName("urn:tva:metadata:extended:2011", "SupportingOS");
    private final static QName _SystemInformationTypeOtherSystemSW_QNAME = new QName("urn:tva:metadata:extended:2011", "OtherSystemSW");
    private final static QName _SystemInformationTypeVirtualMachine_QNAME = new QName("urn:tva:metadata:extended:2011", "VirtualMachine");
    private final static QName _InterstitialContextAttributesTypeMemberOfCampaign_QNAME = new QName("urn:tva:metadata:extended:2011", "MemberOfCampaign");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tva.metadata.extended._2011
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType }
     * 
     */
    public ExtendedContentDescriptionType createExtendedContentDescriptionType() {
        return new ExtendedContentDescriptionType();
    }

    /**
     * Create an instance of {@link RMPITableType }
     * 
     */
    public RMPITableType createRMPITableType() {
        return new RMPITableType();
    }

    /**
     * Create an instance of {@link AgeRangeType }
     * 
     */
    public AgeRangeType createAgeRangeType() {
        return new AgeRangeType();
    }

    /**
     * Create an instance of {@link TargetingInformationType }
     * 
     */
    public TargetingInformationType createTargetingInformationType() {
        return new TargetingInformationType();
    }

    /**
     * Create an instance of {@link ChoiceType }
     * 
     */
    public ChoiceType createChoiceType() {
        return new ChoiceType();
    }

    /**
     * Create an instance of {@link VersionedControlledTermType }
     * 
     */
    public VersionedControlledTermType createVersionedControlledTermType() {
        return new VersionedControlledTermType();
    }

    /**
     * Create an instance of {@link ObjectDescriptionType }
     * 
     */
    public ObjectDescriptionType createObjectDescriptionType() {
        return new ObjectDescriptionType();
    }

    /**
     * Create an instance of {@link NonTVARightsInformationRefType }
     * 
     */
    public NonTVARightsInformationRefType createNonTVARightsInformationRefType() {
        return new NonTVARightsInformationRefType();
    }

    /**
     * Create an instance of {@link CPUType }
     * 
     */
    public CPUType createCPUType() {
        return new CPUType();
    }

    /**
     * Create an instance of {@link UserInformationTableType }
     * 
     */
    public UserInformationTableType createUserInformationTableType() {
        return new UserInformationTableType();
    }

    /**
     * Create an instance of {@link ContentPropertiesType }
     * 
     */
    public ContentPropertiesType createContentPropertiesType() {
        return new ContentPropertiesType();
    }

    /**
     * Create an instance of {@link AnchorType }
     * 
     */
    public AnchorType createAnchorType() {
        return new AnchorType();
    }

    /**
     * Create an instance of {@link CouponRefType }
     * 
     */
    public CouponRefType createCouponRefType() {
        return new CouponRefType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link VideoAttributesType }
     * 
     */
    public VideoAttributesType createVideoAttributesType() {
        return new VideoAttributesType();
    }

    /**
     * Create an instance of {@link TargetPlaceType }
     * 
     */
    public TargetPlaceType createTargetPlaceType() {
        return new TargetPlaceType();
    }

    /**
     * Create an instance of {@link HumidityType }
     * 
     */
    public HumidityType createHumidityType() {
        return new HumidityType();
    }

    /**
     * Create an instance of {@link GameContextAttributesType }
     * 
     */
    public GameContextAttributesType createGameContextAttributesType() {
        return new GameContextAttributesType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link DescriptorType }
     * 
     */
    public DescriptorType createDescriptorType() {
        return new DescriptorType();
    }

    /**
     * Create an instance of {@link RAMType }
     * 
     */
    public RAMType createRAMType() {
        return new RAMType();
    }

    /**
     * Create an instance of {@link ResourceTypeType }
     * 
     */
    public ResourceTypeType createResourceTypeType() {
        return new ResourceTypeType();
    }

    /**
     * Create an instance of {@link DataBroadcastingContextAttributesType }
     * 
     */
    public DataBroadcastingContextAttributesType createDataBroadcastingContextAttributesType() {
        return new DataBroadcastingContextAttributesType();
    }

    /**
     * Create an instance of {@link ContentTargetType }
     * 
     */
    public ContentTargetType createContentTargetType() {
        return new ContentTargetType();
    }

    /**
     * Create an instance of {@link ApplicationContextAttributesType }
     * 
     */
    public ApplicationContextAttributesType createApplicationContextAttributesType() {
        return new ApplicationContextAttributesType();
    }

    /**
     * Create an instance of {@link AccessibilityInformationType }
     * 
     */
    public AccessibilityInformationType createAccessibilityInformationType() {
        return new AccessibilityInformationType();
    }

    /**
     * Create an instance of {@link InterstitialContextAttributesType }
     * 
     */
    public InterstitialContextAttributesType createInterstitialContextAttributesType() {
        return new InterstitialContextAttributesType();
    }

    /**
     * Create an instance of {@link RenderingStyleType }
     * 
     */
    public RenderingStyleType createRenderingStyleType() {
        return new RenderingStyleType();
    }

    /**
     * Create an instance of {@link ExtendedTVAMainType }
     * 
     */
    public ExtendedTVAMainType createExtendedTVAMainType() {
        return new ExtendedTVAMainType();
    }

    /**
     * Create an instance of {@link TargetingInformationTableType }
     * 
     */
    public TargetingInformationTableType createTargetingInformationTableType() {
        return new TargetingInformationTableType();
    }

    /**
     * Create an instance of {@link StillImageContentAttributesType }
     * 
     */
    public StillImageContentAttributesType createStillImageContentAttributesType() {
        return new StillImageContentAttributesType();
    }

    /**
     * Create an instance of {@link CouponDescriptionType }
     * 
     */
    public CouponDescriptionType createCouponDescriptionType() {
        return new CouponDescriptionType();
    }

    /**
     * Create an instance of {@link ExtendedServiceInformationType }
     * 
     */
    public ExtendedServiceInformationType createExtendedServiceInformationType() {
        return new ExtendedServiceInformationType();
    }

    /**
     * Create an instance of {@link ExtendedUserDescriptionType }
     * 
     */
    public ExtendedUserDescriptionType createExtendedUserDescriptionType() {
        return new ExtendedUserDescriptionType();
    }

    /**
     * Create an instance of {@link RequiredCouponType }
     * 
     */
    public RequiredCouponType createRequiredCouponType() {
        return new RequiredCouponType();
    }

    /**
     * Create an instance of {@link RewardCouponType }
     * 
     */
    public RewardCouponType createRewardCouponType() {
        return new RewardCouponType();
    }

    /**
     * Create an instance of {@link NetworkInformationType }
     * 
     */
    public NetworkInformationType createNetworkInformationType() {
        return new NetworkInformationType();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentInformationType }
     * 
     */
    public NaturalEnvironmentInformationType createNaturalEnvironmentInformationType() {
        return new NaturalEnvironmentInformationType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link FilePropertiesType }
     * 
     */
    public FilePropertiesType createFilePropertiesType() {
        return new FilePropertiesType();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link DeclarationsType }
     * 
     */
    public DeclarationsType createDeclarationsType() {
        return new DeclarationsType();
    }

    /**
     * Create an instance of {@link ExtendedRelatedMaterialType }
     * 
     */
    public ExtendedRelatedMaterialType createExtendedRelatedMaterialType() {
        return new ExtendedRelatedMaterialType();
    }

    /**
     * Create an instance of {@link NetworkInformationTableType }
     * 
     */
    public NetworkInformationTableType createNetworkInformationTableType() {
        return new NetworkInformationTableType();
    }

    /**
     * Create an instance of {@link ExtendedPurchaseItemType }
     * 
     */
    public ExtendedPurchaseItemType createExtendedPurchaseItemType() {
        return new ExtendedPurchaseItemType();
    }

    /**
     * Create an instance of {@link SpatialIntervalType }
     * 
     */
    public SpatialIntervalType createSpatialIntervalType() {
        return new SpatialIntervalType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link NaturalEnvironmentInformationTableType }
     * 
     */
    public NaturalEnvironmentInformationTableType createNaturalEnvironmentInformationTableType() {
        return new NaturalEnvironmentInformationTableType();
    }

    /**
     * Create an instance of {@link UsageEnvironmentDescriptionType }
     * 
     */
    public UsageEnvironmentDescriptionType createUsageEnvironmentDescriptionType() {
        return new UsageEnvironmentDescriptionType();
    }

    /**
     * Create an instance of {@link PackageTableType }
     * 
     */
    public PackageTableType createPackageTableType() {
        return new PackageTableType();
    }

    /**
     * Create an instance of {@link HardwareManufacturerType }
     * 
     */
    public HardwareManufacturerType createHardwareManufacturerType() {
        return new HardwareManufacturerType();
    }

    /**
     * Create an instance of {@link RMPIDescriptionType }
     * 
     */
    public RMPIDescriptionType createRMPIDescriptionType() {
        return new RMPIDescriptionType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link ChecksumType }
     * 
     */
    public ChecksumType createChecksumType() {
        return new ChecksumType();
    }

    /**
     * Create an instance of {@link SystemInformationType }
     * 
     */
    public SystemInformationType createSystemInformationType() {
        return new SystemInformationType();
    }

    /**
     * Create an instance of {@link ExtendedSegmentDescriptionType }
     * 
     */
    public ExtendedSegmentDescriptionType createExtendedSegmentDescriptionType() {
        return new ExtendedSegmentDescriptionType();
    }

    /**
     * Create an instance of {@link EducationalContextAttributesType }
     * 
     */
    public EducationalContextAttributesType createEducationalContextAttributesType() {
        return new EducationalContextAttributesType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link CouponTableType }
     * 
     */
    public CouponTableType createCouponTableType() {
        return new CouponTableType();
    }

    /**
     * Create an instance of {@link ExtendedInstanceDescriptionType }
     * 
     */
    public ExtendedInstanceDescriptionType createExtendedInstanceDescriptionType() {
        return new ExtendedInstanceDescriptionType();
    }

    /**
     * Create an instance of {@link SelectionType }
     * 
     */
    public SelectionType createSelectionType() {
        return new SelectionType();
    }

    /**
     * Create an instance of {@link NonTVACouponRefType }
     * 
     */
    public NonTVACouponRefType createNonTVACouponRefType() {
        return new NonTVACouponRefType();
    }

    /**
     * Create an instance of {@link CampaignDescriptionType }
     * 
     */
    public CampaignDescriptionType createCampaignDescriptionType() {
        return new CampaignDescriptionType();
    }

    /**
     * Create an instance of {@link CouponValueType }
     * 
     */
    public CouponValueType createCouponValueType() {
        return new CouponValueType();
    }

    /**
     * Create an instance of {@link TemporalIntervalType }
     * 
     */
    public TemporalIntervalType createTemporalIntervalType() {
        return new TemporalIntervalType();
    }

    /**
     * Create an instance of {@link BiographicInformationType }
     * 
     */
    public BiographicInformationType createBiographicInformationType() {
        return new BiographicInformationType();
    }

    /**
     * Create an instance of {@link TerminalInformationType }
     * 
     */
    public TerminalInformationType createTerminalInformationType() {
        return new TerminalInformationType();
    }

    /**
     * Create an instance of {@link UserInformationType }
     * 
     */
    public UserInformationType createUserInformationType() {
        return new UserInformationType();
    }

    /**
     * Create an instance of {@link AudioAttributesType }
     * 
     */
    public AudioAttributesType createAudioAttributesType() {
        return new AudioAttributesType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link TerminalInformationTableType }
     * 
     */
    public TerminalInformationTableType createTerminalInformationTableType() {
        return new TerminalInformationTableType();
    }

    /**
     * Create an instance of {@link InterstitialCampaignTableType }
     * 
     */
    public InterstitialCampaignTableType createInterstitialCampaignTableType() {
        return new InterstitialCampaignTableType();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType.SourceLocation }
     * 
     */
    public ExtendedContentDescriptionType.SourceLocation createExtendedContentDescriptionTypeSourceLocation() {
        return new ExtendedContentDescriptionType.SourceLocation();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType.MaterialForPrinting }
     * 
     */
    public ExtendedContentDescriptionType.MaterialForPrinting createExtendedContentDescriptionTypeMaterialForPrinting() {
        return new ExtendedContentDescriptionType.MaterialForPrinting();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RAMType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "RAM", scope = SystemInformationType.class)
    public JAXBElement<RAMType> createSystemInformationTypeRAM(RAMType value) {
        return new JAXBElement<RAMType>(_SystemInformationTypeRAM_QNAME, RAMType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CPUType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "CPU", scope = SystemInformationType.class)
    public JAXBElement<CPUType> createSystemInformationTypeCPU(CPUType value) {
        return new JAXBElement<CPUType>(_SystemInformationTypeCPU_QNAME, CPUType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "MiddleWare", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeMiddleWare(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeMiddleWare_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "SupportingOS", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeSupportingOS(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeSupportingOS_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "OtherSystemSW", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeOtherSystemSW(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeOtherSystemSW_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedControlledTermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "VirtualMachine", scope = SystemInformationType.class)
    public JAXBElement<VersionedControlledTermType> createSystemInformationTypeVirtualMachine(VersionedControlledTermType value) {
        return new JAXBElement<VersionedControlledTermType>(_SystemInformationTypeVirtualMachine_QNAME, VersionedControlledTermType.class, SystemInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:extended:2011", name = "MemberOfCampaign", scope = InterstitialContextAttributesType.class)
    public JAXBElement<List<String>> createInterstitialContextAttributesTypeMemberOfCampaign(List<String> value) {
        return new JAXBElement<List<String>>(_InterstitialContextAttributesTypeMemberOfCampaign_QNAME, ((Class) List.class), InterstitialContextAttributesType.class, ((List<String> ) value));
    }

}
