//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(
		xmlns = { 
				@javax.xml.bind.annotation.XmlNs(prefix = "tva2", namespaceURI="urn:tva:metadata:extended:2011")
		}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tva.metadata.extended._2011;
