//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RewardCouponType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RewardCouponType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="CouponRef" type="{urn:tva:metadata:extended:2011}CouponRefType"/>
 *           &lt;element name="CouponDescription" type="{urn:tva:metadata:extended:2011}CouponDescriptionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="userConfirmationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RewardCouponType", propOrder = {
    "couponRef",
    "couponDescription"
})
public class RewardCouponType {

    @XmlElement(name = "CouponRef")
    protected CouponRefType couponRef;
    @XmlElement(name = "CouponDescription")
    protected CouponDescriptionType couponDescription;
    @XmlAttribute(name = "userConfirmationRequired")
    protected Boolean userConfirmationRequired;
    @XmlAttribute(name = "number")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger number;

    /**
     * Gets the value of the couponRef property.
     * 
     * @return
     *     possible object is
     *     {@link CouponRefType }
     *     
     */
    public CouponRefType getCouponRef() {
        return couponRef;
    }

    /**
     * Sets the value of the couponRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponRefType }
     *     
     */
    public void setCouponRef(CouponRefType value) {
        this.couponRef = value;
    }

    /**
     * Gets the value of the couponDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CouponDescriptionType }
     *     
     */
    public CouponDescriptionType getCouponDescription() {
        return couponDescription;
    }

    /**
     * Sets the value of the couponDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponDescriptionType }
     *     
     */
    public void setCouponDescription(CouponDescriptionType value) {
        this.couponDescription = value;
    }

    /**
     * Gets the value of the userConfirmationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUserConfirmationRequired() {
        if (userConfirmationRequired == null) {
            return false;
        } else {
            return userConfirmationRequired;
        }
    }

    /**
     * Sets the value of the userConfirmationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserConfirmationRequired(Boolean value) {
        this.userConfirmationRequired = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        if (number == null) {
            return new BigInteger("1");
        } else {
            return number;
        }
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

}
