//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import tva.rmpi._2011.RMPIMBAndMType;


/**
 * <p>Java class for RMPIDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RMPIDescriptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:rmpi:2011}RMPI-MBAndMType">
 *       &lt;attribute name="RMPIDescriptionId" use="required" type="{urn:tva:metadata:2011}TVAIDType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RMPIDescriptionType")
public class RMPIDescriptionType
    extends RMPIMBAndMType
{

    @XmlAttribute(name = "RMPIDescriptionId", required = true)
    protected String rmpiDescriptionId;

    /**
     * Gets the value of the rmpiDescriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMPIDescriptionId() {
        return rmpiDescriptionId;
    }

    /**
     * Sets the value of the rmpiDescriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMPIDescriptionId(String value) {
        this.rmpiDescriptionId = value;
    }

}
