//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata.extended._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UsageEnvironmentDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsageEnvironmentDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TerminalInformationTable" type="{urn:tva:metadata:extended:2011}TerminalInformationTableType" minOccurs="0"/>
 *         &lt;element name="NetworkInformationTable" type="{urn:tva:metadata:extended:2011}NetworkInformationTableType" minOccurs="0"/>
 *         &lt;element name="NaturalEnvironmentInformationTable" type="{urn:tva:metadata:extended:2011}NaturalEnvironmentInformationTableType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsageEnvironmentDescriptionType", propOrder = {
    "terminalInformationTable",
    "networkInformationTable",
    "naturalEnvironmentInformationTable"
})
public class UsageEnvironmentDescriptionType {

    @XmlElement(name = "TerminalInformationTable")
    protected TerminalInformationTableType terminalInformationTable;
    @XmlElement(name = "NetworkInformationTable")
    protected NetworkInformationTableType networkInformationTable;
    @XmlElement(name = "NaturalEnvironmentInformationTable")
    protected NaturalEnvironmentInformationTableType naturalEnvironmentInformationTable;

    /**
     * Gets the value of the terminalInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link TerminalInformationTableType }
     *     
     */
    public TerminalInformationTableType getTerminalInformationTable() {
        return terminalInformationTable;
    }

    /**
     * Sets the value of the terminalInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminalInformationTableType }
     *     
     */
    public void setTerminalInformationTable(TerminalInformationTableType value) {
        this.terminalInformationTable = value;
    }

    /**
     * Gets the value of the networkInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkInformationTableType }
     *     
     */
    public NetworkInformationTableType getNetworkInformationTable() {
        return networkInformationTable;
    }

    /**
     * Sets the value of the networkInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkInformationTableType }
     *     
     */
    public void setNetworkInformationTable(NetworkInformationTableType value) {
        this.networkInformationTable = value;
    }

    /**
     * Gets the value of the naturalEnvironmentInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalEnvironmentInformationTableType }
     *     
     */
    public NaturalEnvironmentInformationTableType getNaturalEnvironmentInformationTable() {
        return naturalEnvironmentInformationTable;
    }

    /**
     * Sets the value of the naturalEnvironmentInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalEnvironmentInformationTableType }
     *     
     */
    public void setNaturalEnvironmentInformationTable(NaturalEnvironmentInformationTableType value) {
        this.naturalEnvironmentInformationTable = value;
    }

}
