//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:52:02 AM COT 
//


package org.dvb.pcf.pcf_types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.dvb.pcf.pcf.AnimatedImage;
import org.dvb.pcf.pcf.Audio;
import org.dvb.pcf.pcf.AxisLine;
import org.dvb.pcf.pcf.Background;
import org.dvb.pcf.pcf.Boolean;
import org.dvb.pcf.pcf.BooleanArray;
import org.dvb.pcf.pcf.BooleanCookie;
import org.dvb.pcf.pcf.BooleanVar;
import org.dvb.pcf.pcf.Button;
import org.dvb.pcf.pcf.Clock;
import org.dvb.pcf.pcf.Collection;
import org.dvb.pcf.pcf.Color;
import org.dvb.pcf.pcf.ColorArray;
import org.dvb.pcf.pcf.Component;
import org.dvb.pcf.pcf.ConnectStatusImage;
import org.dvb.pcf.pcf.Copy;
import org.dvb.pcf.pcf.Currency;
import org.dvb.pcf.pcf.CurrencyArray;
import org.dvb.pcf.pcf.CurrentTime;
import org.dvb.pcf.pcf.Date;
import org.dvb.pcf.pcf.DateArray;
import org.dvb.pcf.pcf.DateTime;
import org.dvb.pcf.pcf.DateTimeArray;
import org.dvb.pcf.pcf.DateTimeCookie;
import org.dvb.pcf.pcf.DateTimeVar;
import org.dvb.pcf.pcf.ELC;
import org.dvb.pcf.pcf.Ellipse;
import org.dvb.pcf.pcf.Flow;
import org.dvb.pcf.pcf.FontFamily;
import org.dvb.pcf.pcf.FontFamilyArray;
import org.dvb.pcf.pcf.FontSize;
import org.dvb.pcf.pcf.FontSizeArray;
import org.dvb.pcf.pcf.HintTextBox;
import org.dvb.pcf.pcf.Image;
import org.dvb.pcf.pcf.ImageAnimated;
import org.dvb.pcf.pcf.ImageData;
import org.dvb.pcf.pcf.ImageDataArray;
import org.dvb.pcf.pcf.ImageScalable;
import org.dvb.pcf.pcf.Indicate;
import org.dvb.pcf.pcf.Integer;
import org.dvb.pcf.pcf.IntegerArray;
import org.dvb.pcf.pcf.IntegerCookie;
import org.dvb.pcf.pcf.IntegerVar;
import org.dvb.pcf.pcf.Line;
import org.dvb.pcf.pcf.MarkedUpText;
import org.dvb.pcf.pcf.MarkedUpTextArray;
import org.dvb.pcf.pcf.Menu;
import org.dvb.pcf.pcf.NumericNavigator;
import org.dvb.pcf.pcf.OnEventType;
import org.dvb.pcf.pcf.PFC;
import org.dvb.pcf.pcf.PickList;
import org.dvb.pcf.pcf.Pixel;
import org.dvb.pcf.pcf.Polygon;
import org.dvb.pcf.pcf.Position;
import org.dvb.pcf.pcf.PositionArray;
import org.dvb.pcf.pcf.Proportion;
import org.dvb.pcf.pcf.ProportionArray;
import org.dvb.pcf.pcf.RadioButtonGroup;
import org.dvb.pcf.pcf.Random;
import org.dvb.pcf.pcf.Rectangle;
import org.dvb.pcf.pcf.ReturnPath;
import org.dvb.pcf.pcf.SFC;
import org.dvb.pcf.pcf.Scene;
import org.dvb.pcf.pcf.SecureReturnPath;
import org.dvb.pcf.pcf.Service;
import org.dvb.pcf.pcf.Size;
import org.dvb.pcf.pcf.SizeArray;
import org.dvb.pcf.pcf.SpinControl;
import org.dvb.pcf.pcf.StateMachine;
import org.dvb.pcf.pcf.StaticELC;
import org.dvb.pcf.pcf.StaticPFC;
import org.dvb.pcf.pcf.StaticSFC;
import org.dvb.pcf.pcf.StaticTFC;
import org.dvb.pcf.pcf.Stream;
import org.dvb.pcf.pcf.StreamData;
import org.dvb.pcf.pcf.StreamDataArray;
import org.dvb.pcf.pcf.StreamEvent;
import org.dvb.pcf.pcf.String;
import org.dvb.pcf.pcf.StringArray;
import org.dvb.pcf.pcf.StringCookie;
import org.dvb.pcf.pcf.StringVar;
import org.dvb.pcf.pcf.Subtitles;
import org.dvb.pcf.pcf.TB;
import org.dvb.pcf.pcf.TC;
import org.dvb.pcf.pcf.TCG;
import org.dvb.pcf.pcf.TD;
import org.dvb.pcf.pcf.TF;
import org.dvb.pcf.pcf.TFC;
import org.dvb.pcf.pcf.TH;
import org.dvb.pcf.pcf.TR;
import org.dvb.pcf.pcf.Table;
import org.dvb.pcf.pcf.TextBox;
import org.dvb.pcf.pcf.TextFlow;
import org.dvb.pcf.pcf.TextInput;
import org.dvb.pcf.pcf.Ticker;
import org.dvb.pcf.pcf.Time;
import org.dvb.pcf.pcf.TimeArray;
import org.dvb.pcf.pcf.Timecode;
import org.dvb.pcf.pcf.TimecodeArray;
import org.dvb.pcf.pcf.Timer;
import org.dvb.pcf.pcf.TransactionComponent;
import org.dvb.pcf.pcf.URI;
import org.dvb.pcf.pcf.URIArray;
import org.dvb.pcf.pcf.UserKey;
import org.dvb.pcf.pcf.UserKeyArray;
import org.dvb.pcf.pcf.Video;


/**
 * Abstract top-level complex type for collections.
 * 
 * <p>Java class for collectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="collectionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dvb.org/pcf/pcf-types}pcfItemType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.dvb.org/pcf/pcf-types}Reference"/>
 *         &lt;group ref="{http://www.dvb.org/pcf/pcf-types}dataTypes"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "collectionType", propOrder = {
    "referenceOrPrimitiveTypeValueOrConstructedTypeValue"
})
@XmlSeeAlso({
    Collection.class
})
public class CollectionType
    extends PcfItemType
{

    @XmlElementRefs({
        @XmlElementRef(name = "OctetTypeArrayValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BehaviourTypeValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OctetTypeValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CompoundTypeValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ConstructedTypeValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PrimitiveTypeValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ConstructedTypeArrayValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PrimitiveTypeArrayValue", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Reference", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> referenceOrPrimitiveTypeValueOrConstructedTypeValue;

    /**
     * Gets the value of the referenceOrPrimitiveTypeValueOrConstructedTypeValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceOrPrimitiveTypeValueOrConstructedTypeValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceOrPrimitiveTypeValueOrConstructedTypeValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Service }{@code >}
     * {@link JAXBElement }{@code <}{@link Size }{@code >}
     * {@link JAXBElement }{@code <}{@link StaticSFC }{@code >}
     * {@link JAXBElement }{@code <}{@link IntegerArray }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Background }{@code >}
     * {@link JAXBElement }{@code <}{@link IntegerVar }{@code >}
     * {@link JAXBElement }{@code <}{@link StringVar }{@code >}
     * {@link JAXBElement }{@code <}{@link FontSizeArray }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link ReturnPath }{@code >}
     * {@link JAXBElement }{@code <}{@link TFC }{@code >}
     * {@link JAXBElement }{@code <}{@link URI }{@code >}
     * {@link JAXBElement }{@code <}{@link Ellipse }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link TimecodeArray }{@code >}
     * {@link JAXBElement }{@code <}{@link StreamDataArray }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Scene }{@code >}
     * {@link JAXBElement }{@code <}{@link StringCookie }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Image }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link FontFamilyArray }{@code >}
     * {@link JAXBElement }{@code <}{@link AnimatedImage }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link TCG }{@code >}
     * {@link JAXBElement }{@code <}{@link OnEventType }{@code >}
     * {@link JAXBElement }{@code <}{@link ELC }{@code >}
     * {@link JAXBElement }{@code <}{@link HintTextBox }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTime }{@code >}
     * {@link JAXBElement }{@code <}{@link BooleanCookie }{@code >}
     * {@link JAXBElement }{@code <}{@link ConnectStatusImage }{@code >}
     * {@link JAXBElement }{@code <}{@link StaticTFC }{@code >}
     * {@link JAXBElement }{@code <}{@link TC }{@code >}
     * {@link JAXBElement }{@code <}{@link ColorArray }{@code >}
     * {@link JAXBElement }{@code <}{@link TimeArray }{@code >}
     * {@link JAXBElement }{@code <}{@link SpinControl }{@code >}
     * {@link JAXBElement }{@code <}{@link TF }{@code >}
     * {@link JAXBElement }{@code <}{@link Time }{@code >}
     * {@link JAXBElement }{@code <}{@link StaticPFC }{@code >}
     * {@link JAXBElement }{@code <}{@link Component }{@code >}
     * {@link JAXBElement }{@code <}{@link Audio }{@code >}
     * {@link JAXBElement }{@code <}{@link Ticker }{@code >}
     * {@link JAXBElement }{@code <}{@link ImageData }{@code >}
     * {@link JAXBElement }{@code <}{@link TextFlow }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link DateArray }{@code >}
     * {@link JAXBElement }{@code <}{@link ProportionArray }{@code >}
     * {@link JAXBElement }{@code <}{@link IntegerCookie }{@code >}
     * {@link JAXBElement }{@code <}{@link Timecode }{@code >}
     * {@link JAXBElement }{@code <}{@link BooleanArray }{@code >}
     * {@link JAXBElement }{@code <}{@link ImageScalable }{@code >}
     * {@link JAXBElement }{@code <}{@link ImageAnimated }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link StateMachine }{@code >}
     * {@link JAXBElement }{@code <}{@link SFC }{@code >}
     * {@link JAXBElement }{@code <}{@link Timer }{@code >}
     * {@link JAXBElement }{@code <}{@link Rectangle }{@code >}
     * {@link JAXBElement }{@code <}{@link Currency }{@code >}
     * {@link JAXBElement }{@code <}{@link Random }{@code >}
     * {@link JAXBElement }{@code <}{@link Button }{@code >}
     * {@link JAXBElement }{@code <}{@link PickList }{@code >}
     * {@link JAXBElement }{@code <}{@link Subtitles }{@code >}
     * {@link JAXBElement }{@code <}{@link StringArray }{@code >}
     * {@link JAXBElement }{@code <}{@link StreamEvent }{@code >}
     * {@link JAXBElement }{@code <}{@link UserKey }{@code >}
     * {@link JAXBElement }{@code <}{@link PFC }{@code >}
     * {@link JAXBElement }{@code <}{@link Indicate }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TB }{@code >}
     * {@link JAXBElement }{@code <}{@link Table }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeCookie }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeArray }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkedUpTextArray }{@code >}
     * {@link JAXBElement }{@code <}{@link StreamData }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Stream }{@code >}
     * {@link JAXBElement }{@code <}{@link Position }{@code >}
     * {@link JAXBElement }{@code <}{@link Color }{@code >}
     * {@link JAXBElement }{@code <}{@link NumericNavigator }{@code >}
     * {@link JAXBElement }{@code <}{@link Menu }{@code >}
     * {@link JAXBElement }{@code <}{@link Video }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkedUpText }{@code >}
     * {@link JAXBElement }{@code <}{@link FontSize }{@code >}
     * {@link JAXBElement }{@code <}{@link TextInput }{@code >}
     * {@link JAXBElement }{@code <}{@link Proportion }{@code >}
     * {@link JAXBElement }{@code <}{@link Collection }{@code >}
     * {@link JAXBElement }{@code <}{@link UserKeyArray }{@code >}
     * {@link JAXBElement }{@code <}{@link URIArray }{@code >}
     * {@link JAXBElement }{@code <}{@link TR }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link ImageDataArray }{@code >}
     * {@link JAXBElement }{@code <}{@link TH }{@code >}
     * {@link JAXBElement }{@code <}{@link Polygon }{@code >}
     * {@link JAXBElement }{@code <}{@link AxisLine }{@code >}
     * {@link JAXBElement }{@code <}{@link CurrentTime }{@code >}
     * {@link JAXBElement }{@code <}{@link BooleanVar }{@code >}
     * {@link JAXBElement }{@code <}{@link FontFamily }{@code >}
     * {@link JAXBElement }{@code <}{@link StaticELC }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Pixel }{@code >}
     * {@link JAXBElement }{@code <}{@link Copy }{@code >}
     * {@link JAXBElement }{@code <}{@link Flow }{@code >}
     * {@link JAXBElement }{@code <}{@link Line }{@code >}
     * {@link JAXBElement }{@code <}{@link PositionArray }{@code >}
     * {@link JAXBElement }{@code <}{@link Date }{@code >}
     * {@link JAXBElement }{@code <}{@link RadioButtonGroup }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link TextBox }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeVar }{@code >}
     * {@link JAXBElement }{@code <}{@link CurrencyArray }{@code >}
     * {@link JAXBElement }{@code <}{@link TransactionComponent }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link SizeArray }{@code >}
     * {@link JAXBElement }{@code <}{@link TD }{@code >}
     * {@link JAXBElement }{@code <}{@link SecureReturnPath }{@code >}
     * {@link JAXBElement }{@code <}{@link Clock }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getReferenceOrPrimitiveTypeValueOrConstructedTypeValue() {
        if (referenceOrPrimitiveTypeValueOrConstructedTypeValue == null) {
            referenceOrPrimitiveTypeValueOrConstructedTypeValue = new ArrayList<JAXBElement<?>>();
        }
        return this.referenceOrPrimitiveTypeValueOrConstructedTypeValue;
    }

}
