//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:52:02 AM COT 
//


package org.dvb.pcf.pcf_types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.dvb.pcf.pcf.Component;


/**
 * All the properties allowed inside a generic PCF Component (includes class)
 * 
 * <p>Java class for genericComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="genericComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.dvb.org/pcf/pcf-types}componentType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.dvb.org/pcf/pcf-types}Reference"/>
 *         &lt;group ref="{http://www.dvb.org/pcf/pcf-types}dataTypes"/>
 *         &lt;element ref="{http://www.dvb.org/pcf/pcf-types}Parameter"/>
 *       &lt;/choice>
 *       &lt;attribute name="class" use="required" type="{http://www.dvb.org/pcf/pcf-types}name" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "genericComponentType")
@XmlSeeAlso({
    Component.class
})
public class GenericComponentType
    extends ComponentType
{


}
