//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:52:02 AM COT 
//


package org.dvb.pcf.pcf_types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.dvb.pcf.pcf.ImageData;


/**
 * Values containing of referencing image octet data or major MIME type "image".
 * 
 * <p>Java class for imageDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="imageDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dvb.org/pcf/pcf-types}pcfItemType">
 *       &lt;group ref="{http://www.dvb.org/pcf/pcf-types}octetDataContainer"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imageDataType", propOrder = {
    "metaProperty",
    "plainTextData",
    "base64Data",
    "quotedPrintableData",
    "externalBody",
    "hexBinaryData",
    "multipartData"
})
@XmlSeeAlso({
    ImageData.class
})
public class ImageDataType
    extends PcfItemType
{

    @XmlElementRef(name = "MetaProperty", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> metaProperty;
    @XmlElementRef(name = "PlainTextData", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected JAXBElement<?> plainTextData;
    @XmlElement(name = "Base64Data")
    protected Base64Data base64Data;
    @XmlElementRef(name = "QuotedPrintableData", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected JAXBElement<?> quotedPrintableData;
    @XmlElementRef(name = "ExternalBody", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected JAXBElement<?> externalBody;
    @XmlElementRef(name = "HexBinaryData", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected JAXBElement<?> hexBinaryData;
    @XmlElementRef(name = "MultipartData", namespace = "http://www.dvb.org/pcf/pcf-types", type = JAXBElement.class, required = false)
    protected JAXBElement<?> multipartData;

    /**
     * Gets the value of the metaProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metaProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetaProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link MetaPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getMetaProperty() {
        if (metaProperty == null) {
            metaProperty = new ArrayList<JAXBElement<?>>();
        }
        return this.metaProperty;
    }

    /**
     * Gets the value of the plainTextData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<?> getPlainTextData() {
        return plainTextData;
    }

    /**
     * Sets the value of the plainTextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPlainTextData(JAXBElement<?> value) {
        this.plainTextData = value;
    }

    /**
     * Gets the value of the base64Data property.
     * 
     * @return
     *     possible object is
     *     {@link Base64Data }
     *     
     */
    public Base64Data getBase64Data() {
        return base64Data;
    }

    /**
     * Sets the value of the base64Data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64Data }
     *     
     */
    public void setBase64Data(Base64Data value) {
        this.base64Data = value;
    }

    /**
     * Gets the value of the quotedPrintableData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QuotedPrintableDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getQuotedPrintableData() {
        return quotedPrintableData;
    }

    /**
     * Sets the value of the quotedPrintableData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QuotedPrintableDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setQuotedPrintableData(JAXBElement<?> value) {
        this.quotedPrintableData = value;
    }

    /**
     * Gets the value of the externalBody property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExternalBodyType }{@code >}
     *     
     */
    public JAXBElement<?> getExternalBody() {
        return externalBody;
    }

    /**
     * Sets the value of the externalBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExternalBodyType }{@code >}
     *     
     */
    public void setExternalBody(JAXBElement<?> value) {
        this.externalBody = value;
    }

    /**
     * Gets the value of the hexBinaryData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link HexBinaryDataType }{@code >}
     *     
     */
    public JAXBElement<?> getHexBinaryData() {
        return hexBinaryData;
    }

    /**
     * Sets the value of the hexBinaryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link HexBinaryDataType }{@code >}
     *     
     */
    public void setHexBinaryData(JAXBElement<?> value) {
        this.hexBinaryData = value;
    }

    /**
     * Gets the value of the multipartData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MultipartDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<?> getMultipartData() {
        return multipartData;
    }

    /**
     * Sets the value of the multipartData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MultipartDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setMultipartData(JAXBElement<?> value) {
        this.multipartData = value;
    }

}
