//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:52:02 AM COT 
//


package org.dvb.pcf.pcf_types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.dvb.pcf.pcf.BooleanArray;
import org.dvb.pcf.pcf.ColorArray;
import org.dvb.pcf.pcf.CurrencyArray;
import org.dvb.pcf.pcf.DateArray;
import org.dvb.pcf.pcf.DateTimeArray;
import org.dvb.pcf.pcf.FontFamilyArray;
import org.dvb.pcf.pcf.FontSizeArray;
import org.dvb.pcf.pcf.ImageDataArray;
import org.dvb.pcf.pcf.IntegerArray;
import org.dvb.pcf.pcf.MarkedUpTextArray;
import org.dvb.pcf.pcf.PositionArray;
import org.dvb.pcf.pcf.ProportionArray;
import org.dvb.pcf.pcf.SizeArray;
import org.dvb.pcf.pcf.StreamDataArray;
import org.dvb.pcf.pcf.StringArray;
import org.dvb.pcf.pcf.TimeArray;
import org.dvb.pcf.pcf.TimecodeArray;
import org.dvb.pcf.pcf.URIArray;
import org.dvb.pcf.pcf.UserKeyArray;


/**
 * <p>Java class for pcfItemArrayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pcfItemArrayType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dvb.org/pcf/pcf-types}pcfItemType">
 *       &lt;attGroup ref="{http://www.dvb.org/pcf/pcf-types}arrayAttrs"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pcfItemArrayType")
@XmlSeeAlso({
    DateTimeArray.class,
    ColorArray.class,
    ProportionArray.class,
    PositionArray.class,
    DateArray.class,
    BooleanArray.class,
    ImageDataArray.class,
    URIArray.class,
    IntegerArray.class,
    FontSizeArray.class,
    CurrencyArray.class,
    FontFamilyArray.class,
    MarkedUpTextArray.class,
    UserKeyArray.class,
    TimeArray.class,
    StringArray.class,
    StreamDataArray.class,
    TimecodeArray.class,
    SizeArray.class
})
public class PcfItemArrayType
    extends PcfItemType
{

    @XmlAttribute(name = "length")
    protected Integer length;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLength(Integer value) {
        this.length = value;
    }

}
