//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreationCoordinatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreationCoordinatesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreationDate" type="{urn:tva:metadata:2011}TVATimeType" minOccurs="0"/>
 *         &lt;element name="CreationLocation" type="{urn:tva:mpeg7:2008}regionCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreationCoordinatesType", propOrder = {
    "creationDate",
    "creationLocation"
})
public class CreationCoordinatesType {

    @XmlElement(name = "CreationDate")
    protected TVATimeType creationDate;
    @XmlElement(name = "CreationLocation")
    protected String creationLocation;

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link TVATimeType }
     *     
     */
    public TVATimeType getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVATimeType }
     *     
     */
    public void setCreationDate(TVATimeType value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the creationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationLocation() {
        return creationLocation;
    }

    /**
     * Sets the value of the creationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationLocation(String value) {
        this.creationLocation = value;
    }

}
