//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import tva.mpeg7._2008.PersonNameType;
import tva.mpeg7._2008.TextualType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tva.metadata._2011 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TVAMain_QNAME = new QName("urn:tva:metadata:2011", "TVAMain");
    private final static QName _TVAAgentTypePersonName_QNAME = new QName("urn:tva:metadata:2011", "PersonName");
    private final static QName _TVAAgentTypePersonNameIDRef_QNAME = new QName("urn:tva:metadata:2011", "PersonNameIDRef");
    private final static QName _TVAAgentTypeOrganizationName_QNAME = new QName("urn:tva:metadata:2011", "OrganizationName");
    private final static QName _TVAAgentTypeOrganizationNameIDRef_QNAME = new QName("urn:tva:metadata:2011", "OrganizationNameIDRef");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tva.metadata._2011
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TVATermDefinitionType }
     * 
     */
    public TVATermDefinitionType createTVATermDefinitionType() {
        return new TVATermDefinitionType();
    }

    /**
     * Create an instance of {@link PurchaseType }
     * 
     */
    public PurchaseType createPurchaseType() {
        return new PurchaseType();
    }

    /**
     * Create an instance of {@link TVAContentLinks }
     * 
     */
    public TVAContentLinks createTVAContentLinks() {
        return new TVAContentLinks();
    }

    /**
     * Create an instance of {@link RelatedMaterialType }
     * 
     */
    public RelatedMaterialType createRelatedMaterialType() {
        return new RelatedMaterialType();
    }

    /**
     * Create an instance of {@link TVAMainType }
     * 
     */
    public TVAMainType createTVAMainType() {
        return new TVAMainType();
    }

    /**
     * Create an instance of {@link AspectRatioType }
     * 
     */
    public AspectRatioType createAspectRatioType() {
        return new AspectRatioType();
    }

    /**
     * Create an instance of {@link SegmentReferenceType }
     * 
     */
    public SegmentReferenceType createSegmentReferenceType() {
        return new SegmentReferenceType();
    }

    /**
     * Create an instance of {@link PurchaseItemType }
     * 
     */
    public PurchaseItemType createPurchaseItemType() {
        return new PurchaseItemType();
    }

    /**
     * Create an instance of {@link ShortTitleType }
     * 
     */
    public ShortTitleType createShortTitleType() {
        return new ShortTitleType();
    }

    /**
     * Create an instance of {@link ColorType }
     * 
     */
    public ColorType createColorType() {
        return new ColorType();
    }

    /**
     * Create an instance of {@link AggregationOfType }
     * 
     */
    public AggregationOfType createAggregationOfType() {
        return new AggregationOfType();
    }

    /**
     * Create an instance of {@link ScheduleEventType }
     * 
     */
    public ScheduleEventType createScheduleEventType() {
        return new ScheduleEventType();
    }

    /**
     * Create an instance of {@link DerivationReasonType }
     * 
     */
    public DerivationReasonType createDerivationReasonType() {
        return new DerivationReasonType();
    }

    /**
     * Create an instance of {@link CaptioningAttributesType }
     * 
     */
    public CaptioningAttributesType createCaptioningAttributesType() {
        return new CaptioningAttributesType();
    }

    /**
     * Create an instance of {@link ControlledTermType }
     * 
     */
    public ControlledTermType createControlledTermType() {
        return new ControlledTermType();
    }

    /**
     * Create an instance of {@link ServiceInformationNameType }
     * 
     */
    public ServiceInformationNameType createServiceInformationNameType() {
        return new ServiceInformationNameType();
    }

    /**
     * Create an instance of {@link ServiceRefType }
     * 
     */
    public ServiceRefType createServiceRefType() {
        return new ServiceRefType();
    }

    /**
     * Create an instance of {@link SegmentGroupInformationType }
     * 
     */
    public SegmentGroupInformationType createSegmentGroupInformationType() {
        return new SegmentGroupInformationType();
    }

    /**
     * Create an instance of {@link FlagType }
     * 
     */
    public FlagType createFlagType() {
        return new FlagType();
    }

    /**
     * Create an instance of {@link PushDownloadType }
     * 
     */
    public PushDownloadType createPushDownloadType() {
        return new PushDownloadType();
    }

    /**
     * Create an instance of {@link TVAAgentType }
     * 
     */
    public TVAAgentType createTVAAgentType() {
        return new TVAAgentType();
    }

    /**
     * Create an instance of {@link AVAttributesType }
     * 
     */
    public AVAttributesType createAVAttributesType() {
        return new AVAttributesType();
    }

    /**
     * Create an instance of {@link BasicSegmentDescriptionType }
     * 
     */
    public BasicSegmentDescriptionType createBasicSegmentDescriptionType() {
        return new BasicSegmentDescriptionType();
    }

    /**
     * Create an instance of {@link GroupInformationType }
     * 
     */
    public GroupInformationType createGroupInformationType() {
        return new GroupInformationType();
    }

    /**
     * Create an instance of {@link ReleaseInformationType }
     * 
     */
    public ReleaseInformationType createReleaseInformationType() {
        return new ReleaseInformationType();
    }

    /**
     * Create an instance of {@link UsageHistoryType }
     * 
     */
    public UsageHistoryType createUsageHistoryType() {
        return new UsageHistoryType();
    }

    /**
     * Create an instance of {@link CaptionLanguageType }
     * 
     */
    public CaptionLanguageType createCaptionLanguageType() {
        return new CaptionLanguageType();
    }

    /**
     * Create an instance of {@link SegmentGroupTypeType }
     * 
     */
    public SegmentGroupTypeType createSegmentGroupTypeType() {
        return new SegmentGroupTypeType();
    }

    /**
     * Create an instance of {@link ScheduleType }
     * 
     */
    public ScheduleType createScheduleType() {
        return new ScheduleType();
    }

    /**
     * Create an instance of {@link AwardType }
     * 
     */
    public AwardType createAwardType() {
        return new AwardType();
    }

    /**
     * Create an instance of {@link GenericDerivationReasonType }
     * 
     */
    public GenericDerivationReasonType createGenericDerivationReasonType() {
        return new GenericDerivationReasonType();
    }

    /**
     * Create an instance of {@link CreditsListType }
     * 
     */
    public CreditsListType createCreditsListType() {
        return new CreditsListType();
    }

    /**
     * Create an instance of {@link OrganizationNameType }
     * 
     */
    public OrganizationNameType createOrganizationNameType() {
        return new OrganizationNameType();
    }

    /**
     * Create an instance of {@link TVAPlaceType }
     * 
     */
    public TVAPlaceType createTVAPlaceType() {
        return new TVAPlaceType();
    }

    /**
     * Create an instance of {@link GroupIntervalType }
     * 
     */
    public GroupIntervalType createGroupIntervalType() {
        return new GroupIntervalType();
    }

    /**
     * Create an instance of {@link SegmentsType }
     * 
     */
    public SegmentsType createSegmentsType() {
        return new SegmentsType();
    }

    /**
     * Create an instance of {@link ReviewType }
     * 
     */
    public ReviewType createReviewType() {
        return new ReviewType();
    }

    /**
     * Create an instance of {@link GroupsType }
     * 
     */
    public GroupsType createGroupsType() {
        return new GroupsType();
    }

    /**
     * Create an instance of {@link ClassificationSchemeTableType }
     * 
     */
    public ClassificationSchemeTableType createClassificationSchemeTableType() {
        return new ClassificationSchemeTableType();
    }

    /**
     * Create an instance of {@link TVAMediaTimeType }
     * 
     */
    public TVAMediaTimeType createTVAMediaTimeType() {
        return new TVAMediaTimeType();
    }

    /**
     * Create an instance of {@link ReviewerType }
     * 
     */
    public ReviewerType createReviewerType() {
        return new ReviewerType();
    }

    /**
     * Create an instance of {@link SignLanguageType }
     * 
     */
    public SignLanguageType createSignLanguageType() {
        return new SignLanguageType();
    }

    /**
     * Create an instance of {@link TVATimeType }
     * 
     */
    public TVATimeType createTVATimeType() {
        return new TVATimeType();
    }

    /**
     * Create an instance of {@link ProgramDescriptionType }
     * 
     */
    public ProgramDescriptionType createProgramDescriptionType() {
        return new ProgramDescriptionType();
    }

    /**
     * Create an instance of {@link MetadataOriginationInformationTableType }
     * 
     */
    public MetadataOriginationInformationTableType createMetadataOriginationInformationTableType() {
        return new MetadataOriginationInformationTableType();
    }

    /**
     * Create an instance of {@link ProgramLocationTableType }
     * 
     */
    public ProgramLocationTableType createProgramLocationTableType() {
        return new ProgramLocationTableType();
    }

    /**
     * Create an instance of {@link ServiceInformationType }
     * 
     */
    public ServiceInformationType createServiceInformationType() {
        return new ServiceInformationType();
    }

    /**
     * Create an instance of {@link ExplanationType }
     * 
     */
    public ExplanationType createExplanationType() {
        return new ExplanationType();
    }

    /**
     * Create an instance of {@link AudioLanguageType }
     * 
     */
    public AudioLanguageType createAudioLanguageType() {
        return new AudioLanguageType();
    }

    /**
     * Create an instance of {@link BasicContentDescriptionType }
     * 
     */
    public BasicContentDescriptionType createBasicContentDescriptionType() {
        return new BasicContentDescriptionType();
    }

    /**
     * Create an instance of {@link TimeBaseReferenceType }
     * 
     */
    public TimeBaseReferenceType createTimeBaseReferenceType() {
        return new TimeBaseReferenceType();
    }

    /**
     * Create an instance of {@link TermNameType }
     * 
     */
    public TermNameType createTermNameType() {
        return new TermNameType();
    }

    /**
     * Create an instance of {@link CreationCoordinatesType }
     * 
     */
    public CreationCoordinatesType createCreationCoordinatesType() {
        return new CreationCoordinatesType();
    }

    /**
     * Create an instance of {@link CreditsInformationTableType }
     * 
     */
    public CreditsInformationTableType createCreditsInformationTableType() {
        return new CreditsInformationTableType();
    }

    /**
     * Create an instance of {@link CreditsItemType }
     * 
     */
    public CreditsItemType createCreditsItemType() {
        return new CreditsItemType();
    }

    /**
     * Create an instance of {@link PurchaseInformationType }
     * 
     */
    public PurchaseInformationType createPurchaseInformationType() {
        return new PurchaseInformationType();
    }

    /**
     * Create an instance of {@link TVAMediaRelIncrTimePointType }
     * 
     */
    public TVAMediaRelIncrTimePointType createTVAMediaRelIncrTimePointType() {
        return new TVAMediaRelIncrTimePointType();
    }

    /**
     * Create an instance of {@link MetadataOriginationInformationType }
     * 
     */
    public MetadataOriginationInformationType createMetadataOriginationInformationType() {
        return new MetadataOriginationInformationType();
    }

    /**
     * Create an instance of {@link DRMDeclarationType }
     * 
     */
    public DRMDeclarationType createDRMDeclarationType() {
        return new DRMDeclarationType();
    }

    /**
     * Create an instance of {@link GenreType }
     * 
     */
    public GenreType createGenreType() {
        return new GenreType();
    }

    /**
     * Create an instance of {@link VideoAttributesType }
     * 
     */
    public VideoAttributesType createVideoAttributesType() {
        return new VideoAttributesType();
    }

    /**
     * Create an instance of {@link SegmentGroupListType }
     * 
     */
    public SegmentGroupListType createSegmentGroupListType() {
        return new SegmentGroupListType();
    }

    /**
     * Create an instance of {@link ProgramInformationType }
     * 
     */
    public ProgramInformationType createProgramInformationType() {
        return new ProgramInformationType();
    }

    /**
     * Create an instance of {@link ProgramReviewTableType }
     * 
     */
    public ProgramReviewTableType createProgramReviewTableType() {
        return new ProgramReviewTableType();
    }

    /**
     * Create an instance of {@link TVAClassificationSchemeType }
     * 
     */
    public TVAClassificationSchemeType createTVAClassificationSchemeType() {
        return new TVAClassificationSchemeType();
    }

    /**
     * Create an instance of {@link InstanceDescriptionType }
     * 
     */
    public InstanceDescriptionType createInstanceDescriptionType() {
        return new InstanceDescriptionType();
    }

    /**
     * Create an instance of {@link AwardsListItemType }
     * 
     */
    public AwardsListItemType createAwardsListItemType() {
        return new AwardsListItemType();
    }

    /**
     * Create an instance of {@link UserActionListType }
     * 
     */
    public UserActionListType createUserActionListType() {
        return new UserActionListType();
    }

    /**
     * Create an instance of {@link ReleaseDateType }
     * 
     */
    public ReleaseDateType createReleaseDateType() {
        return new ReleaseDateType();
    }

    /**
     * Create an instance of {@link BitRateType }
     * 
     */
    public BitRateType createBitRateType() {
        return new BitRateType();
    }

    /**
     * Create an instance of {@link UserActionType }
     * 
     */
    public UserActionType createUserActionType() {
        return new UserActionType();
    }

    /**
     * Create an instance of {@link TVAPersonNameType }
     * 
     */
    public TVAPersonNameType createTVAPersonNameType() {
        return new TVAPersonNameType();
    }

    /**
     * Create an instance of {@link MediaReviewType }
     * 
     */
    public MediaReviewType createMediaReviewType() {
        return new MediaReviewType();
    }

    /**
     * Create an instance of {@link TVAIDRefElementType }
     * 
     */
    public TVAIDRefElementType createTVAIDRefElementType() {
        return new TVAIDRefElementType();
    }

    /**
     * Create an instance of {@link GroupInformationTableType }
     * 
     */
    public GroupInformationTableType createGroupInformationTableType() {
        return new GroupInformationTableType();
    }

    /**
     * Create an instance of {@link SegmentInformationTableType }
     * 
     */
    public SegmentInformationTableType createSegmentInformationTableType() {
        return new SegmentInformationTableType();
    }

    /**
     * Create an instance of {@link MemberOfType }
     * 
     */
    public MemberOfType createMemberOfType() {
        return new MemberOfType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link PurchaseInformationTableType }
     * 
     */
    public PurchaseInformationTableType createPurchaseInformationTableType() {
        return new PurchaseInformationTableType();
    }

    /**
     * Create an instance of {@link AwardsListType }
     * 
     */
    public AwardsListType createAwardsListType() {
        return new AwardsListType();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link PurchaseListType }
     * 
     */
    public PurchaseListType createPurchaseListType() {
        return new PurchaseListType();
    }

    /**
     * Create an instance of {@link DerivedFromType }
     * 
     */
    public DerivedFromType createDerivedFromType() {
        return new DerivedFromType();
    }

    /**
     * Create an instance of {@link BroadcastEventType }
     * 
     */
    public BroadcastEventType createBroadcastEventType() {
        return new BroadcastEventType();
    }

    /**
     * Create an instance of {@link EpisodeOfType }
     * 
     */
    public EpisodeOfType createEpisodeOfType() {
        return new EpisodeOfType();
    }

    /**
     * Create an instance of {@link SegmentInformationType }
     * 
     */
    public SegmentInformationType createSegmentInformationType() {
        return new SegmentInformationType();
    }

    /**
     * Create an instance of {@link CSAliasType }
     * 
     */
    public CSAliasType createCSAliasType() {
        return new CSAliasType();
    }

    /**
     * Create an instance of {@link ServiceInformationTableType }
     * 
     */
    public ServiceInformationTableType createServiceInformationTableType() {
        return new ServiceInformationTableType();
    }

    /**
     * Create an instance of {@link SynopsisType }
     * 
     */
    public SynopsisType createSynopsisType() {
        return new SynopsisType();
    }

    /**
     * Create an instance of {@link MappingTermType }
     * 
     */
    public MappingTermType createMappingTermType() {
        return new MappingTermType();
    }

    /**
     * Create an instance of {@link OnDemandProgramType }
     * 
     */
    public OnDemandProgramType createOnDemandProgramType() {
        return new OnDemandProgramType();
    }

    /**
     * Create an instance of {@link ValidPeriodType }
     * 
     */
    public ValidPeriodType createValidPeriodType() {
        return new ValidPeriodType();
    }

    /**
     * Create an instance of {@link CRIDRefType }
     * 
     */
    public CRIDRefType createCRIDRefType() {
        return new CRIDRefType();
    }

    /**
     * Create an instance of {@link DepictedCoordinatesType }
     * 
     */
    public DepictedCoordinatesType createDepictedCoordinatesType() {
        return new DepictedCoordinatesType();
    }

    /**
     * Create an instance of {@link TVAParentalGuidanceType }
     * 
     */
    public TVAParentalGuidanceType createTVAParentalGuidanceType() {
        return new TVAParentalGuidanceType();
    }

    /**
     * Create an instance of {@link UserDescriptionType }
     * 
     */
    public UserDescriptionType createUserDescriptionType() {
        return new UserDescriptionType();
    }

    /**
     * Create an instance of {@link SegmentListType }
     * 
     */
    public SegmentListType createSegmentListType() {
        return new SegmentListType();
    }

    /**
     * Create an instance of {@link ProgramInformationTableType }
     * 
     */
    public ProgramInformationTableType createProgramInformationTableType() {
        return new ProgramInformationTableType();
    }

    /**
     * Create an instance of {@link AudioAttributesType }
     * 
     */
    public AudioAttributesType createAudioAttributesType() {
        return new AudioAttributesType();
    }

    /**
     * Create an instance of {@link OnDemandServiceType }
     * 
     */
    public OnDemandServiceType createOnDemandServiceType() {
        return new OnDemandServiceType();
    }

    /**
     * Create an instance of {@link ProgramGroupTypeType }
     * 
     */
    public ProgramGroupTypeType createProgramGroupTypeType() {
        return new ProgramGroupTypeType();
    }

    /**
     * Create an instance of {@link UserActionHistoryType }
     * 
     */
    public UserActionHistoryType createUserActionHistoryType() {
        return new UserActionHistoryType();
    }

    /**
     * Create an instance of {@link tva.metadata._2011.TVATermDefinitionBaseType.Name }
     * 
     */
    public tva.metadata._2011.TVATermDefinitionBaseType.Name createTVATermDefinitionBaseTypeName() {
        return new tva.metadata._2011.TVATermDefinitionBaseType.Name();
    }

    /**
     * Create an instance of {@link tva.metadata._2011.TVATermDefinitionBaseType.EquivalentCSTerm }
     * 
     */
    public tva.metadata._2011.TVATermDefinitionBaseType.EquivalentCSTerm createTVATermDefinitionBaseTypeEquivalentCSTerm() {
        return new tva.metadata._2011.TVATermDefinitionBaseType.EquivalentCSTerm();
    }

    /**
     * Create an instance of {@link TVATermDefinitionType.Term }
     * 
     */
    public TVATermDefinitionType.Term createTVATermDefinitionTypeTerm() {
        return new TVATermDefinitionType.Term();
    }

    /**
     * Create an instance of {@link PurchaseType.QuantityRange }
     * 
     */
    public PurchaseType.QuantityRange createPurchaseTypeQuantityRange() {
        return new PurchaseType.QuantityRange();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAMainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2011", name = "TVAMain")
    public JAXBElement<TVAMainType> createTVAMain(TVAMainType value) {
        return new JAXBElement<TVAMainType>(_TVAMain_QNAME, TVAMainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2011", name = "PersonName", scope = TVAAgentType.class)
    public JAXBElement<PersonNameType> createTVAAgentTypePersonName(PersonNameType value) {
        return new JAXBElement<PersonNameType>(_TVAAgentTypePersonName_QNAME, PersonNameType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2011", name = "PersonNameIDRef", scope = TVAAgentType.class)
    public JAXBElement<TVAIDRefElementType> createTVAAgentTypePersonNameIDRef(TVAIDRefElementType value) {
        return new JAXBElement<TVAIDRefElementType>(_TVAAgentTypePersonNameIDRef_QNAME, TVAIDRefElementType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextualType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2011", name = "OrganizationName", scope = TVAAgentType.class)
    public JAXBElement<TextualType> createTVAAgentTypeOrganizationName(TextualType value) {
        return new JAXBElement<TextualType>(_TVAAgentTypeOrganizationName_QNAME, TextualType.class, TVAAgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:tva:metadata:2011", name = "OrganizationNameIDRef", scope = TVAAgentType.class)
    public JAXBElement<TVAIDRefElementType> createTVAAgentTypeOrganizationNameIDRef(TVAIDRefElementType value) {
        return new JAXBElement<TVAIDRefElementType>(_TVAAgentTypeOrganizationNameIDRef_QNAME, TVAIDRefElementType.class, TVAAgentType.class, value);
    }

}
