//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import edu.eafit.maestria.activa.metadata.ExtendedProgramDescriptionType;


/**
 * <p>Java class for ProgramDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProgramDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProgramInformationTable" type="{urn:tva:metadata:2011}ProgramInformationTableType" minOccurs="0"/>
 *         &lt;element name="GroupInformationTable" type="{urn:tva:metadata:2011}GroupInformationTableType" minOccurs="0"/>
 *         &lt;element name="ProgramLocationTable" type="{urn:tva:metadata:2011}ProgramLocationTableType" minOccurs="0"/>
 *         &lt;element name="ServiceInformationTable" type="{urn:tva:metadata:2011}ServiceInformationTableType" minOccurs="0"/>
 *         &lt;element name="CreditsInformationTable" type="{urn:tva:metadata:2011}CreditsInformationTableType" minOccurs="0"/>
 *         &lt;element name="ProgramReviewTable" type="{urn:tva:metadata:2011}ProgramReviewTableType" minOccurs="0"/>
 *         &lt;element name="SegmentInformationTable" type="{urn:tva:metadata:2011}SegmentInformationTableType" minOccurs="0"/>
 *         &lt;element name="PurchaseInformationTable" type="{urn:tva:metadata:2011}PurchaseInformationTableType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgramDescriptionType", propOrder = {
    "programInformationTable",
    "groupInformationTable",
    "programLocationTable",
    "serviceInformationTable",
    "creditsInformationTable",
    "programReviewTable",
    "segmentInformationTable",
    "purchaseInformationTable"
})
@XmlSeeAlso({
    ExtendedProgramDescriptionType.class
})
public class ProgramDescriptionType {

    @XmlElement(name = "ProgramInformationTable")
    protected ProgramInformationTableType programInformationTable;
    @XmlElement(name = "GroupInformationTable")
    protected GroupInformationTableType groupInformationTable;
    @XmlElement(name = "ProgramLocationTable")
    protected ProgramLocationTableType programLocationTable;
    @XmlElement(name = "ServiceInformationTable")
    protected ServiceInformationTableType serviceInformationTable;
    @XmlElement(name = "CreditsInformationTable")
    protected CreditsInformationTableType creditsInformationTable;
    @XmlElement(name = "ProgramReviewTable")
    protected ProgramReviewTableType programReviewTable;
    @XmlElement(name = "SegmentInformationTable")
    protected SegmentInformationTableType segmentInformationTable;
    @XmlElement(name = "PurchaseInformationTable")
    protected PurchaseInformationTableType purchaseInformationTable;

    /**
     * Gets the value of the programInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramInformationTableType }
     *     
     */
    public ProgramInformationTableType getProgramInformationTable() {
        return programInformationTable;
    }

    /**
     * Sets the value of the programInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramInformationTableType }
     *     
     */
    public void setProgramInformationTable(ProgramInformationTableType value) {
        this.programInformationTable = value;
    }

    /**
     * Gets the value of the groupInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link GroupInformationTableType }
     *     
     */
    public GroupInformationTableType getGroupInformationTable() {
        return groupInformationTable;
    }

    /**
     * Sets the value of the groupInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupInformationTableType }
     *     
     */
    public void setGroupInformationTable(GroupInformationTableType value) {
        this.groupInformationTable = value;
    }

    /**
     * Gets the value of the programLocationTable property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramLocationTableType }
     *     
     */
    public ProgramLocationTableType getProgramLocationTable() {
        return programLocationTable;
    }

    /**
     * Sets the value of the programLocationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramLocationTableType }
     *     
     */
    public void setProgramLocationTable(ProgramLocationTableType value) {
        this.programLocationTable = value;
    }

    /**
     * Gets the value of the serviceInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceInformationTableType }
     *     
     */
    public ServiceInformationTableType getServiceInformationTable() {
        return serviceInformationTable;
    }

    /**
     * Sets the value of the serviceInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceInformationTableType }
     *     
     */
    public void setServiceInformationTable(ServiceInformationTableType value) {
        this.serviceInformationTable = value;
    }

    /**
     * Gets the value of the creditsInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsInformationTableType }
     *     
     */
    public CreditsInformationTableType getCreditsInformationTable() {
        return creditsInformationTable;
    }

    /**
     * Sets the value of the creditsInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsInformationTableType }
     *     
     */
    public void setCreditsInformationTable(CreditsInformationTableType value) {
        this.creditsInformationTable = value;
    }

    /**
     * Gets the value of the programReviewTable property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramReviewTableType }
     *     
     */
    public ProgramReviewTableType getProgramReviewTable() {
        return programReviewTable;
    }

    /**
     * Sets the value of the programReviewTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramReviewTableType }
     *     
     */
    public void setProgramReviewTable(ProgramReviewTableType value) {
        this.programReviewTable = value;
    }

    /**
     * Gets the value of the segmentInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentInformationTableType }
     *     
     */
    public SegmentInformationTableType getSegmentInformationTable() {
        return segmentInformationTable;
    }

    /**
     * Sets the value of the segmentInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentInformationTableType }
     *     
     */
    public void setSegmentInformationTable(SegmentInformationTableType value) {
        this.segmentInformationTable = value;
    }

    /**
     * Gets the value of the purchaseInformationTable property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseInformationTableType }
     *     
     */
    public PurchaseInformationTableType getPurchaseInformationTable() {
        return purchaseInformationTable;
    }

    /**
     * Sets the value of the purchaseInformationTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseInformationTableType }
     *     
     */
    public void setPurchaseInformationTable(PurchaseInformationTableType value) {
        this.purchaseInformationTable = value;
    }

}
