//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import tva.mpeg7._2008.UniqueIDType;


/**
 * <p>Java class for ProgramInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProgramInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BasicDescription" type="{urn:tva:metadata:2011}BasicContentDescriptionType"/>
 *         &lt;element name="OtherIdentifier" type="{urn:tva:mpeg7:2008}UniqueIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AVAttributes" type="{urn:tva:metadata:2011}AVAttributesType" minOccurs="0"/>
 *         &lt;element name="MemberOf" type="{urn:tva:metadata:2011}BaseMemberOfType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DerivedFrom" type="{urn:tva:metadata:2011}DerivedFromType" minOccurs="0"/>
 *         &lt;element name="EpisodeOf" type="{urn:tva:metadata:2011}EpisodeOfType" minOccurs="0"/>
 *         &lt;element name="PartOfAggregatedProgram" type="{urn:tva:metadata:2011}CRIDType" minOccurs="0"/>
 *         &lt;element name="AggregationOf" type="{urn:tva:metadata:2011}AggregationOfType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:tva:metadata:2011}fragmentIdentification"/>
 *       &lt;attribute name="programId" use="required" type="{urn:tva:metadata:2011}CRIDType" />
 *       &lt;attribute name="metadataOriginIDRef" type="{urn:tva:metadata:2011}TVAIDRefType" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgramInformationType", propOrder = {
    "basicDescription",
    "otherIdentifier",
    "avAttributes",
    "memberOf",
    "derivedFrom",
    "episodeOf",
    "partOfAggregatedProgram",
    "aggregationOf"
})
public class ProgramInformationType {

    @XmlElement(name = "BasicDescription", required = true)
    protected BasicContentDescriptionType basicDescription;
    @XmlElement(name = "OtherIdentifier")
    protected List<UniqueIDType> otherIdentifier;
    @XmlElement(name = "AVAttributes")
    protected AVAttributesType avAttributes;
    @XmlElement(name = "MemberOf")
    protected List<BaseMemberOfType> memberOf;
    @XmlElement(name = "DerivedFrom")
    protected DerivedFromType derivedFrom;
    @XmlElement(name = "EpisodeOf")
    protected EpisodeOfType episodeOf;
    @XmlElement(name = "PartOfAggregatedProgram")
    protected String partOfAggregatedProgram;
    @XmlElement(name = "AggregationOf")
    protected AggregationOfType aggregationOf;
    @XmlAttribute(name = "programId", required = true)
    protected String programId;
    @XmlAttribute(name = "metadataOriginIDRef")
    protected String metadataOriginIDRef;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlAttribute(name = "fragmentId")
    protected String fragmentId;
    @XmlAttribute(name = "fragmentVersion")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger fragmentVersion;
    @XmlAttribute(name = "fragmentExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fragmentExpirationDate;

    /**
     * Gets the value of the basicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BasicContentDescriptionType }
     *     
     */
    public BasicContentDescriptionType getBasicDescription() {
        return basicDescription;
    }

    /**
     * Sets the value of the basicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicContentDescriptionType }
     *     
     */
    public void setBasicDescription(BasicContentDescriptionType value) {
        this.basicDescription = value;
    }

    /**
     * Gets the value of the otherIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueIDType }
     * 
     * 
     */
    public List<UniqueIDType> getOtherIdentifier() {
        if (otherIdentifier == null) {
            otherIdentifier = new ArrayList<UniqueIDType>();
        }
        return this.otherIdentifier;
    }

    /**
     * Gets the value of the avAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link AVAttributesType }
     *     
     */
    public AVAttributesType getAVAttributes() {
        return avAttributes;
    }

    /**
     * Sets the value of the avAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AVAttributesType }
     *     
     */
    public void setAVAttributes(AVAttributesType value) {
        this.avAttributes = value;
    }

    /**
     * Gets the value of the memberOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseMemberOfType }
     * 
     * 
     */
    public List<BaseMemberOfType> getMemberOf() {
        if (memberOf == null) {
            memberOf = new ArrayList<BaseMemberOfType>();
        }
        return this.memberOf;
    }

    /**
     * Gets the value of the derivedFrom property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedFromType }
     *     
     */
    public DerivedFromType getDerivedFrom() {
        return derivedFrom;
    }

    /**
     * Sets the value of the derivedFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedFromType }
     *     
     */
    public void setDerivedFrom(DerivedFromType value) {
        this.derivedFrom = value;
    }

    /**
     * Gets the value of the episodeOf property.
     * 
     * @return
     *     possible object is
     *     {@link EpisodeOfType }
     *     
     */
    public EpisodeOfType getEpisodeOf() {
        return episodeOf;
    }

    /**
     * Sets the value of the episodeOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpisodeOfType }
     *     
     */
    public void setEpisodeOf(EpisodeOfType value) {
        this.episodeOf = value;
    }

    /**
     * Gets the value of the partOfAggregatedProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartOfAggregatedProgram() {
        return partOfAggregatedProgram;
    }

    /**
     * Sets the value of the partOfAggregatedProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartOfAggregatedProgram(String value) {
        this.partOfAggregatedProgram = value;
    }

    /**
     * Gets the value of the aggregationOf property.
     * 
     * @return
     *     possible object is
     *     {@link AggregationOfType }
     *     
     */
    public AggregationOfType getAggregationOf() {
        return aggregationOf;
    }

    /**
     * Sets the value of the aggregationOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregationOfType }
     *     
     */
    public void setAggregationOf(AggregationOfType value) {
        this.aggregationOf = value;
    }

    /**
     * Gets the value of the programId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * Sets the value of the programId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramId(String value) {
        this.programId = value;
    }

    /**
     * Gets the value of the metadataOriginIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataOriginIDRef() {
        return metadataOriginIDRef;
    }

    /**
     * Sets the value of the metadataOriginIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataOriginIDRef(String value) {
        this.metadataOriginIDRef = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the fragmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFragmentId() {
        return fragmentId;
    }

    /**
     * Sets the value of the fragmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFragmentId(String value) {
        this.fragmentId = value;
    }

    /**
     * Gets the value of the fragmentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFragmentVersion() {
        return fragmentVersion;
    }

    /**
     * Sets the value of the fragmentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFragmentVersion(BigInteger value) {
        this.fragmentVersion = value;
    }

    /**
     * Gets the value of the fragmentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFragmentExpirationDate() {
        return fragmentExpirationDate;
    }

    /**
     * Sets the value of the fragmentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFragmentExpirationDate(XMLGregorianCalendar value) {
        this.fragmentExpirationDate = value;
    }

}
