//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SegmentGroupTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentGroupTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:metadata:2011}BaseSegmentGroupTypeType">
 *       &lt;attribute name="value" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="highlights"/>
 *             &lt;enumeration value="highlights/objects"/>
 *             &lt;enumeration value="highlights/events"/>
 *             &lt;enumeration value="bookmarks"/>
 *             &lt;enumeration value="bookmarks/objects"/>
 *             &lt;enumeration value="bookmarks/events"/>
 *             &lt;enumeration value="themeGroup"/>
 *             &lt;enumeration value="preview"/>
 *             &lt;enumeration value="preview/title"/>
 *             &lt;enumeration value="preview/slideshow"/>
 *             &lt;enumeration value="tableOfContents"/>
 *             &lt;enumeration value="synopsis"/>
 *             &lt;enumeration value="shots"/>
 *             &lt;enumeration value="insertionPoints"/>
 *             &lt;enumeration value="alternativeGroups"/>
 *             &lt;enumeration value="alternativeSegments"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentGroupTypeType")
public class SegmentGroupTypeType
    extends BaseSegmentGroupTypeType
{

    @XmlAttribute(name = "value", required = true)
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
