//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import tva.mpeg7._2008.TextualType;


/**
 * <p>Java class for SynopsisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SynopsisType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:tva:mpeg7:2008>TextualType">
 *       &lt;attribute name="length" type="{urn:tva:metadata:2011}SynopsisLengthType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SynopsisType")
public class SynopsisType
    extends TextualType
{

    @XmlAttribute(name = "length")
    protected SynopsisLengthType length;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link SynopsisLengthType }
     *     
     */
    public SynopsisLengthType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynopsisLengthType }
     *     
     */
    public void setLength(SynopsisLengthType value) {
        this.length = value;
    }

}
