//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import tva.mpeg7._2008.PersonNameType;
import tva.mpeg7._2008.TextualType;


/**
 * <p>Java class for TVAAgentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TVAAgentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PersonName" type="{urn:tva:mpeg7:2008}PersonNameType"/>
 *           &lt;element name="PersonNameIDRef" type="{urn:tva:metadata:2011}TVAIDRefElementType"/>
 *           &lt;element name="OrganizationName" type="{urn:tva:mpeg7:2008}TextualType"/>
 *           &lt;element name="OrganizationNameIDRef" type="{urn:tva:metadata:2011}TVAIDRefElementType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVAAgentType", propOrder = {
    "personNameOrPersonNameIDRefOrOrganizationName"
})
@XmlSeeAlso({
    ReviewerType.class,
    CreditsItemType.class
})
public class TVAAgentType {

    @XmlElementRefs({
        @XmlElementRef(name = "OrganizationNameIDRef", namespace = "urn:tva:metadata:2011", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PersonName", namespace = "urn:tva:metadata:2011", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PersonNameIDRef", namespace = "urn:tva:metadata:2011", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OrganizationName", namespace = "urn:tva:metadata:2011", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> personNameOrPersonNameIDRefOrOrganizationName;

    /**
     * Gets the value of the personNameOrPersonNameIDRefOrOrganizationName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personNameOrPersonNameIDRefOrOrganizationName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonNameOrPersonNameIDRefOrOrganizationName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link TVAIDRefElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link TextualType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getPersonNameOrPersonNameIDRefOrOrganizationName() {
        if (personNameOrPersonNameIDRefOrOrganizationName == null) {
            personNameOrPersonNameIDRefOrOrganizationName = new ArrayList<JAXBElement<?>>();
        }
        return this.personNameOrPersonNameIDRefOrOrganizationName;
    }

}
