//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.metadata._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import tva.metadata.extended._2011.ExtendedUserDescriptionType;
import tva.mpeg7._2008.UserPreferencesType;


/**
 * <p>Java class for UserDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserPreferences" type="{urn:tva:mpeg7:2008}UserPreferencesType" minOccurs="0"/>
 *         &lt;element name="UsageHistory" type="{urn:tva:metadata:2011}UsageHistoryType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDescriptionType", propOrder = {
    "userPreferences",
    "usageHistory"
})
@XmlSeeAlso({
    ExtendedUserDescriptionType.class
})
public class UserDescriptionType {

    @XmlElement(name = "UserPreferences")
    protected UserPreferencesType userPreferences;
    @XmlElement(name = "UsageHistory")
    protected UsageHistoryType usageHistory;

    /**
     * Gets the value of the userPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link UserPreferencesType }
     *     
     */
    public UserPreferencesType getUserPreferences() {
        return userPreferences;
    }

    /**
     * Sets the value of the userPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPreferencesType }
     *     
     */
    public void setUserPreferences(UserPreferencesType value) {
        this.userPreferences = value;
    }

    /**
     * Gets the value of the usageHistory property.
     * 
     * @return
     *     possible object is
     *     {@link UsageHistoryType }
     *     
     */
    public UsageHistoryType getUsageHistory() {
        return usageHistory;
    }

    /**
     * Sets the value of the usageHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageHistoryType }
     *     
     */
    public void setUsageHistory(UsageHistoryType value) {
        this.usageHistory = value;
    }

}
