//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package edu.eafit.maestria.activa.metadata.mpeg7;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.eafit.maestria.activa.metadata.mpeg7 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.eafit.maestria.activa.metadata.mpeg7
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegionLocatorType }
     * 
     */
    public RegionLocatorType createRegionLocatorType() {
        return new RegionLocatorType();
    }

    /**
     * Create an instance of {@link BoxListType }
     * 
     */
    public BoxListType createBoxListType() {
        return new BoxListType();
    }

    /**
     * Create an instance of {@link IntegerMatrixType }
     * 
     */
    public IntegerMatrixType createIntegerMatrixType() {
        return new IntegerMatrixType();
    }

    /**
     * Create an instance of {@link RegionLocatorType.CoordRef }
     * 
     */
    public RegionLocatorType.CoordRef createRegionLocatorTypeCoordRef() {
        return new RegionLocatorType.CoordRef();
    }

    /**
     * Create an instance of {@link RegionLocatorType.Box }
     * 
     */
    public RegionLocatorType.Box createRegionLocatorTypeBox() {
        return new RegionLocatorType.Box();
    }

    /**
     * Create an instance of {@link RegionLocatorType.Polygon }
     * 
     */
    public RegionLocatorType.Polygon createRegionLocatorTypePolygon() {
        return new RegionLocatorType.Polygon();
    }

}
