//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.26 at 11:01:21 AM COT 
//


package edu.eafit.maestria.activa.metadata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.eafit.maestria.activa.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.eafit.maestria.activa.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link EntityInformationTableType }
     * 
     */
    public EntityInformationTableType createEntityInformationTableType() {
        return new EntityInformationTableType();
    }

    /**
     * Create an instance of {@link ExtendedSegmentInformationType }
     * 
     */
    public ExtendedSegmentInformationType createExtendedSegmentInformationType() {
        return new ExtendedSegmentInformationType();
    }

    /**
     * Create an instance of {@link ExtendedProgramDescriptionType }
     * 
     */
    public ExtendedProgramDescriptionType createExtendedProgramDescriptionType() {
        return new ExtendedProgramDescriptionType();
    }

    /**
     * Create an instance of {@link EntityRegionType }
     * 
     */
    public EntityRegionType createEntityRegionType() {
        return new EntityRegionType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link PropertiesType.Property }
     * 
     */
    public PropertiesType.Property createPropertiesTypeProperty() {
        return new PropertiesType.Property();
    }

    /**
     * Create an instance of {@link ResourcesType.Resource }
     * 
     */
    public ResourcesType.Resource createResourcesTypeResource() {
        return new ResourcesType.Resource();
    }

}
