//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.rmpi._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import tva.metadata._2011.ControlledTermType;


/**
 * <p>Java class for AncillaryRMPIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AncillaryRMPIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RMPITypeFlag" type="{urn:tva:rmpi:2011}RMITypeFlagType"/>
 *         &lt;element name="VersionOfRMPI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OriginOfRMPI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cipher" type="{urn:tva:metadata:2011}ControlledTermType"/>
 *         &lt;choice>
 *           &lt;element name="MBScramblingControl" type="{urn:tva:rmpi:2011}MBScramblingControlType"/>
 *           &lt;element name="MScramblingControl" type="{urn:tva:rmpi:2011}MScramblingControlType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AncillaryRMPIType", propOrder = {
    "rmpiTypeFlag",
    "versionOfRMPI",
    "originOfRMPI",
    "cipher",
    "mbScramblingControl",
    "mScramblingControl"
})
public class AncillaryRMPIType {

    @XmlElement(name = "RMPITypeFlag", required = true)
    protected RMITypeFlagType rmpiTypeFlag;
    @XmlElement(name = "VersionOfRMPI", required = true)
    protected String versionOfRMPI;
    @XmlElement(name = "OriginOfRMPI", required = true)
    protected String originOfRMPI;
    @XmlElement(name = "Cipher", required = true)
    protected ControlledTermType cipher;
    @XmlElement(name = "MBScramblingControl")
    protected MBScramblingControlType mbScramblingControl;
    @XmlElement(name = "MScramblingControl")
    protected MScramblingControlType mScramblingControl;

    /**
     * Gets the value of the rmpiTypeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link RMITypeFlagType }
     *     
     */
    public RMITypeFlagType getRMPITypeFlag() {
        return rmpiTypeFlag;
    }

    /**
     * Sets the value of the rmpiTypeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMITypeFlagType }
     *     
     */
    public void setRMPITypeFlag(RMITypeFlagType value) {
        this.rmpiTypeFlag = value;
    }

    /**
     * Gets the value of the versionOfRMPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionOfRMPI() {
        return versionOfRMPI;
    }

    /**
     * Sets the value of the versionOfRMPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionOfRMPI(String value) {
        this.versionOfRMPI = value;
    }

    /**
     * Gets the value of the originOfRMPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginOfRMPI() {
        return originOfRMPI;
    }

    /**
     * Sets the value of the originOfRMPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginOfRMPI(String value) {
        this.originOfRMPI = value;
    }

    /**
     * Gets the value of the cipher property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledTermType }
     *     
     */
    public ControlledTermType getCipher() {
        return cipher;
    }

    /**
     * Sets the value of the cipher property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledTermType }
     *     
     */
    public void setCipher(ControlledTermType value) {
        this.cipher = value;
    }

    /**
     * Gets the value of the mbScramblingControl property.
     * 
     * @return
     *     possible object is
     *     {@link MBScramblingControlType }
     *     
     */
    public MBScramblingControlType getMBScramblingControl() {
        return mbScramblingControl;
    }

    /**
     * Sets the value of the mbScramblingControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBScramblingControlType }
     *     
     */
    public void setMBScramblingControl(MBScramblingControlType value) {
        this.mbScramblingControl = value;
    }

    /**
     * Gets the value of the mScramblingControl property.
     * 
     * @return
     *     possible object is
     *     {@link MScramblingControlType }
     *     
     */
    public MScramblingControlType getMScramblingControl() {
        return mScramblingControl;
    }

    /**
     * Sets the value of the mScramblingControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link MScramblingControlType }
     *     
     */
    public void setMScramblingControl(MScramblingControlType value) {
        this.mScramblingControl = value;
    }

}
