//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.rmpi._2011;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityLevelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityLevelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="level 0"/>
 *     &lt;enumeration value="level 1"/>
 *     &lt;enumeration value="level 2"/>
 *     &lt;enumeration value="level 3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecurityLevelType")
@XmlEnum
public enum SecurityLevelType {

    @XmlEnumValue("level 0")
    LEVEL_0("level 0"),
    @XmlEnumValue("level 1")
    LEVEL_1("level 1"),
    @XmlEnumValue("level 2")
    LEVEL_2("level 2"),
    @XmlEnumValue("level 3")
    LEVEL_3("level 3");
    private final String value;

    SecurityLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SecurityLevelType fromValue(String v) {
        for (SecurityLevelType c: SecurityLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
