//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 05:28:03 PM COT 
//


package tva.rmpi._2011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimultaneousRenderingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimultaneousRenderingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SimultaneousRenderingFlag" type="{urn:tva:rmpi:2011}ControlType"/>
 *         &lt;element name="SimultaneousRenderingCount" type="{urn:tva:rmpi:2011}SimultaneousRenderingCountType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimultaneousRenderingType", propOrder = {
    "simultaneousRenderingFlag",
    "simultaneousRenderingCount"
})
public class SimultaneousRenderingType {

    @XmlElement(name = "SimultaneousRenderingFlag", required = true)
    protected ControlType simultaneousRenderingFlag;
    @XmlElement(name = "SimultaneousRenderingCount")
    protected int simultaneousRenderingCount;

    /**
     * Gets the value of the simultaneousRenderingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link ControlType }
     *     
     */
    public ControlType getSimultaneousRenderingFlag() {
        return simultaneousRenderingFlag;
    }

    /**
     * Sets the value of the simultaneousRenderingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlType }
     *     
     */
    public void setSimultaneousRenderingFlag(ControlType value) {
        this.simultaneousRenderingFlag = value;
    }

    /**
     * Gets the value of the simultaneousRenderingCount property.
     * 
     */
    public int getSimultaneousRenderingCount() {
        return simultaneousRenderingCount;
    }

    /**
     * Sets the value of the simultaneousRenderingCount property.
     * 
     */
    public void setSimultaneousRenderingCount(int value) {
        this.simultaneousRenderingCount = value;
    }

}
